// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: media.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const countTotalMedia = `-- name: CountTotalMedia :one
SELECT COUNT(*) AS total FROM media
`

func (q *Queries) CountTotalMedia(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTotalMedia)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (
    name,
    description,
    alt,
    media_path,
    user_id,
    file_size,
    mime_type,
    width,
    height,
    duration,
    original_filename
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, name, description, alt, media_path, user_id, created_at, changed_at, file_size, mime_type, width, height, duration, original_filename, metadata
`

type CreateMediaParams struct {
	Name             string `json:"name"`
	Description      string `json:"description"`
	Alt              string `json:"alt"`
	MediaPath        string `json:"media_path"`
	UserID           int64  `json:"user_id"`
	FileSize         int64  `json:"file_size"`
	MimeType         string `json:"mime_type"`
	Width            int32  `json:"width"`
	Height           int32  `json:"height"`
	Duration         int32  `json:"duration"`
	OriginalFilename string `json:"original_filename"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRowContext(ctx, createMedia,
		arg.Name,
		arg.Description,
		arg.Alt,
		arg.MediaPath,
		arg.UserID,
		arg.FileSize,
		arg.MimeType,
		arg.Width,
		arg.Height,
		arg.Duration,
		arg.OriginalFilename,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Alt,
		&i.MediaPath,
		&i.UserID,
		&i.CreatedAt,
		&i.ChangedAt,
		&i.FileSize,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.Duration,
		&i.OriginalFilename,
		&i.Metadata,
	)
	return i, err
}

const createPostMedia = `-- name: CreatePostMedia :one
INSERT INTO post_media (
    post_id,
    media_id,
    "order"
) VALUES (
    $1, $2, $3
)
ON CONFLICT (post_id, media_id)
DO UPDATE SET "order" = EXCLUDED."order"
RETURNING post_id, media_id, "order"
`

type CreatePostMediaParams struct {
	PostID  int64 `json:"post_id"`
	MediaID int64 `json:"media_id"`
	Order   int32 `json:"order"`
}

func (q *Queries) CreatePostMedia(ctx context.Context, arg CreatePostMediaParams) (PostMedium, error) {
	row := q.db.QueryRowContext(ctx, createPostMedia, arg.PostID, arg.MediaID, arg.Order)
	var i PostMedium
	err := row.Scan(&i.PostID, &i.MediaID, &i.Order)
	return i, err
}

const deleteMedia = `-- name: DeleteMedia :exec
DELETE FROM media
WHERE id = $1
`

func (q *Queries) DeleteMedia(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMedia, id)
	return err
}

const deleteMediaByUserID = `-- name: DeleteMediaByUserID :exec
DELETE FROM media
WHERE user_id = $1
`

func (q *Queries) DeleteMediaByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMediaByUserID, userID)
	return err
}

const deleteMediaPosts = `-- name: DeleteMediaPosts :exec
DELETE FROM post_media
WHERE media_id = $1
`

func (q *Queries) DeleteMediaPosts(ctx context.Context, mediaID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMediaPosts, mediaID)
	return err
}

const deletePostMedia = `-- name: DeletePostMedia :exec
DELETE FROM post_media
WHERE post_id = $1 AND media_id = $2
`

type DeletePostMediaParams struct {
	PostID  int64 `json:"post_id"`
	MediaID int64 `json:"media_id"`
}

func (q *Queries) DeletePostMedia(ctx context.Context, arg DeletePostMediaParams) error {
	_, err := q.db.ExecContext(ctx, deletePostMedia, arg.PostID, arg.MediaID)
	return err
}

const deletePostMediaByOrder = `-- name: DeletePostMediaByOrder :exec
DELETE FROM post_media 
WHERE post_id = $1 AND "order" = $2
`

type DeletePostMediaByOrderParams struct {
	PostID int64 `json:"post_id"`
	Order  int32 `json:"order"`
}

func (q *Queries) DeletePostMediaByOrder(ctx context.Context, arg DeletePostMediaByOrderParams) error {
	_, err := q.db.ExecContext(ctx, deletePostMediaByOrder, arg.PostID, arg.Order)
	return err
}

const deletePostMedias = `-- name: DeletePostMedias :exec
DELETE FROM post_media
WHERE post_id = $1
`

func (q *Queries) DeletePostMedias(ctx context.Context, postID int64) error {
	_, err := q.db.ExecContext(ctx, deletePostMedias, postID)
	return err
}

const getFeaturedImage = `-- name: GetFeaturedImage :one
SELECT 
    pm.post_id,
    pm.media_id,
    pm."order",
    m.name,
    m.description,
    m.alt,
    m.media_path,
    m.width,
    m.height,
    m.file_size,
    m.mime_type,
    m.original_filename,
    m.created_at,
    m.changed_at
FROM post_media pm
JOIN media m ON pm.media_id = m.id
WHERE pm.post_id = $1 AND pm."order" = 0
LIMIT 1
`

type GetFeaturedImageRow struct {
	PostID           int64     `json:"post_id"`
	MediaID          int64     `json:"media_id"`
	Order            int32     `json:"order"`
	Name             string    `json:"name"`
	Description      string    `json:"description"`
	Alt              string    `json:"alt"`
	MediaPath        string    `json:"media_path"`
	Width            int32     `json:"width"`
	Height           int32     `json:"height"`
	FileSize         int64     `json:"file_size"`
	MimeType         string    `json:"mime_type"`
	OriginalFilename string    `json:"original_filename"`
	CreatedAt        time.Time `json:"created_at"`
	ChangedAt        time.Time `json:"changed_at"`
}

func (q *Queries) GetFeaturedImage(ctx context.Context, postID int64) (GetFeaturedImageRow, error) {
	row := q.db.QueryRowContext(ctx, getFeaturedImage, postID)
	var i GetFeaturedImageRow
	err := row.Scan(
		&i.PostID,
		&i.MediaID,
		&i.Order,
		&i.Name,
		&i.Description,
		&i.Alt,
		&i.MediaPath,
		&i.Width,
		&i.Height,
		&i.FileSize,
		&i.MimeType,
		&i.OriginalFilename,
		&i.CreatedAt,
		&i.ChangedAt,
	)
	return i, err
}

const getMedia = `-- name: GetMedia :one
SELECT id, name, description, alt, media_path, user_id, created_at, changed_at, file_size, mime_type, width, height, duration, original_filename, metadata FROM media
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMedia(ctx context.Context, id int64) (Medium, error) {
	row := q.db.QueryRowContext(ctx, getMedia, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Alt,
		&i.MediaPath,
		&i.UserID,
		&i.CreatedAt,
		&i.ChangedAt,
		&i.FileSize,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.Duration,
		&i.OriginalFilename,
		&i.Metadata,
	)
	return i, err
}

const getMediaByPost = `-- name: GetMediaByPost :many
SELECT m.id, m.name, m.description, m.alt, m.media_path, m.user_id, m.created_at, m.changed_at, m.file_size, m.mime_type, m.width, m.height, m.duration, m.original_filename, m.metadata FROM media m
JOIN post_media pm ON m.id = pm.media_id
WHERE pm.post_id = $1
ORDER BY pm."order", m.created_at
`

func (q *Queries) GetMediaByPost(ctx context.Context, postID int64) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, getMediaByPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medium{}
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Alt,
			&i.MediaPath,
			&i.UserID,
			&i.CreatedAt,
			&i.ChangedAt,
			&i.FileSize,
			&i.MimeType,
			&i.Width,
			&i.Height,
			&i.Duration,
			&i.OriginalFilename,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMediaByPostWithOrder = `-- name: GetMediaByPostWithOrder :many
SELECT 
    m.id, m.name, m.description, m.alt, m.media_path, m.user_id, m.created_at, m.changed_at, m.file_size, m.mime_type, m.width, m.height, m.duration, m.original_filename, m.metadata,
    pm."order" as media_order
FROM media m
JOIN post_media pm ON m.id = pm.media_id
WHERE pm.post_id = $1
ORDER BY pm."order", m.created_at
`

type GetMediaByPostWithOrderRow struct {
	ID               int64           `json:"id"`
	Name             string          `json:"name"`
	Description      string          `json:"description"`
	Alt              string          `json:"alt"`
	MediaPath        string          `json:"media_path"`
	UserID           int64           `json:"user_id"`
	CreatedAt        time.Time       `json:"created_at"`
	ChangedAt        time.Time       `json:"changed_at"`
	FileSize         int64           `json:"file_size"`
	MimeType         string          `json:"mime_type"`
	Width            int32           `json:"width"`
	Height           int32           `json:"height"`
	Duration         int32           `json:"duration"`
	OriginalFilename string          `json:"original_filename"`
	Metadata         json.RawMessage `json:"metadata"`
	MediaOrder       int32           `json:"media_order"`
}

func (q *Queries) GetMediaByPostWithOrder(ctx context.Context, postID int64) ([]GetMediaByPostWithOrderRow, error) {
	rows, err := q.db.QueryContext(ctx, getMediaByPostWithOrder, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMediaByPostWithOrderRow{}
	for rows.Next() {
		var i GetMediaByPostWithOrderRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Alt,
			&i.MediaPath,
			&i.UserID,
			&i.CreatedAt,
			&i.ChangedAt,
			&i.FileSize,
			&i.MimeType,
			&i.Width,
			&i.Height,
			&i.Duration,
			&i.OriginalFilename,
			&i.Metadata,
			&i.MediaOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMediaByUser = `-- name: GetMediaByUser :many
SELECT 
    m.id, m.name, m.description, m.alt, m.media_path, m.user_id, m.created_at, m.changed_at, m.file_size, m.mime_type, m.width, m.height, m.duration, m.original_filename, m.metadata,
    COUNT(pm.post_id) as post_count
FROM media m
LEFT JOIN post_media pm ON m.id = pm.media_id
WHERE 
    m.user_id = $1
    AND ($2 = '' OR m.mime_type LIKE $2 || '%')
    AND ($3 = '' OR (m.name ILIKE '%' || $3 || '%' OR m.description ILIKE '%' || $3 || '%'))
GROUP BY m.id, m.name, m.description, m.alt, m.media_path, m.user_id, m.created_at, m.changed_at, m.file_size, m.mime_type, m.width, m.height, m.duration, m.original_filename, m.metadata
ORDER BY 
    CASE WHEN $4 = 'date_asc' THEN m.created_at END ASC,
    CASE WHEN $4 = 'date_desc' THEN m.created_at END DESC,
    CASE WHEN $4 = 'name_asc' THEN m.name END ASC,
    CASE WHEN $4 = 'name_desc' THEN m.name END DESC,
    CASE WHEN $4 = 'size_asc' THEN m.file_size END ASC,
    CASE WHEN $4 = 'size_desc' THEN m.file_size END DESC,
    CASE WHEN $4 = 'type_asc' THEN m.mime_type END ASC,
    CASE WHEN $4 = 'type_desc' THEN m.mime_type END DESC,
    CASE WHEN $4 = 'posts_asc' THEN COUNT(pm.post_id) END ASC,
    CASE WHEN $4 = 'posts_desc' THEN COUNT(pm.post_id) END DESC,
    m.created_at DESC
LIMIT $5
OFFSET $6
`

type GetMediaByUserParams struct {
	UserID  int64       `json:"user_id"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Column4 interface{} `json:"column_4"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type GetMediaByUserRow struct {
	ID               int64           `json:"id"`
	Name             string          `json:"name"`
	Description      string          `json:"description"`
	Alt              string          `json:"alt"`
	MediaPath        string          `json:"media_path"`
	UserID           int64           `json:"user_id"`
	CreatedAt        time.Time       `json:"created_at"`
	ChangedAt        time.Time       `json:"changed_at"`
	FileSize         int64           `json:"file_size"`
	MimeType         string          `json:"mime_type"`
	Width            int32           `json:"width"`
	Height           int32           `json:"height"`
	Duration         int32           `json:"duration"`
	OriginalFilename string          `json:"original_filename"`
	Metadata         json.RawMessage `json:"metadata"`
	PostCount        int64           `json:"post_count"`
}

func (q *Queries) GetMediaByUser(ctx context.Context, arg GetMediaByUserParams) ([]GetMediaByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getMediaByUser,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMediaByUserRow{}
	for rows.Next() {
		var i GetMediaByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Alt,
			&i.MediaPath,
			&i.UserID,
			&i.CreatedAt,
			&i.ChangedAt,
			&i.FileSize,
			&i.MimeType,
			&i.Width,
			&i.Height,
			&i.Duration,
			&i.OriginalFilename,
			&i.Metadata,
			&i.PostCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMediaPostCount = `-- name: GetMediaPostCount :one
SELECT COUNT(*) FROM post_media
WHERE media_id = $1
`

func (q *Queries) GetMediaPostCount(ctx context.Context, mediaID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMediaPostCount, mediaID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPopularMedia = `-- name: GetPopularMedia :many
SELECT 
    m.id, m.name, m.description, m.alt, m.media_path, m.user_id, m.created_at, m.changed_at, m.file_size, m.mime_type, m.width, m.height, m.duration, m.original_filename, m.metadata,
    COUNT(pm.post_id) as post_count
FROM media m
JOIN post_media pm ON m.id = pm.media_id
GROUP BY m.id, m.name, m.description, m.alt, m.media_path, m.user_id, m.created_at, m.changed_at, m.file_size, m.mime_type, m.width, m.height, m.duration, m.original_filename, m.metadata
HAVING COUNT(pm.post_id) > 0
ORDER BY COUNT(pm.post_id) DESC
LIMIT $1
`

type GetPopularMediaRow struct {
	ID               int64           `json:"id"`
	Name             string          `json:"name"`
	Description      string          `json:"description"`
	Alt              string          `json:"alt"`
	MediaPath        string          `json:"media_path"`
	UserID           int64           `json:"user_id"`
	CreatedAt        time.Time       `json:"created_at"`
	ChangedAt        time.Time       `json:"changed_at"`
	FileSize         int64           `json:"file_size"`
	MimeType         string          `json:"mime_type"`
	Width            int32           `json:"width"`
	Height           int32           `json:"height"`
	Duration         int32           `json:"duration"`
	OriginalFilename string          `json:"original_filename"`
	Metadata         json.RawMessage `json:"metadata"`
	PostCount        int64           `json:"post_count"`
}

func (q *Queries) GetPopularMedia(ctx context.Context, limit int32) ([]GetPopularMediaRow, error) {
	rows, err := q.db.QueryContext(ctx, getPopularMedia, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPopularMediaRow{}
	for rows.Next() {
		var i GetPopularMediaRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Alt,
			&i.MediaPath,
			&i.UserID,
			&i.CreatedAt,
			&i.ChangedAt,
			&i.FileSize,
			&i.MimeType,
			&i.Width,
			&i.Height,
			&i.Duration,
			&i.OriginalFilename,
			&i.Metadata,
			&i.PostCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostMedia = `-- name: GetPostMedia :many
SELECT 
    pm.post_id,
    pm.media_id,
    pm."order",
    m.name,
    m.description,
    m.alt,
    m.media_path,
    m.width,
    m.height,
    m.file_size,
    m.mime_type,
    m.original_filename,
    m.user_id,
    m.created_at,
    m.changed_at
FROM post_media pm
JOIN media m ON pm.media_id = m.id
WHERE pm.post_id = $1
ORDER BY pm."order", pm.media_id
`

type GetPostMediaRow struct {
	PostID           int64     `json:"post_id"`
	MediaID          int64     `json:"media_id"`
	Order            int32     `json:"order"`
	Name             string    `json:"name"`
	Description      string    `json:"description"`
	Alt              string    `json:"alt"`
	MediaPath        string    `json:"media_path"`
	Width            int32     `json:"width"`
	Height           int32     `json:"height"`
	FileSize         int64     `json:"file_size"`
	MimeType         string    `json:"mime_type"`
	OriginalFilename string    `json:"original_filename"`
	UserID           int64     `json:"user_id"`
	CreatedAt        time.Time `json:"created_at"`
	ChangedAt        time.Time `json:"changed_at"`
}

func (q *Queries) GetPostMedia(ctx context.Context, postID int64) ([]GetPostMediaRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostMedia, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPostMediaRow{}
	for rows.Next() {
		var i GetPostMediaRow
		if err := rows.Scan(
			&i.PostID,
			&i.MediaID,
			&i.Order,
			&i.Name,
			&i.Description,
			&i.Alt,
			&i.MediaPath,
			&i.Width,
			&i.Height,
			&i.FileSize,
			&i.MimeType,
			&i.OriginalFilename,
			&i.UserID,
			&i.CreatedAt,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostMediaCount = `-- name: GetPostMediaCount :one
SELECT COUNT(*) FROM post_media
WHERE post_id = $1
`

func (q *Queries) GetPostMediaCount(ctx context.Context, postID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPostMediaCount, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPostWithMedia = `-- name: GetPostWithMedia :one
SELECT 
    p.id, p.title, p.description, p.user_id, p.username, p.url, p.post_type, p.post_status, p.post_parent, p.menu_order, p.created_at, p.changed_at, p.block_doc, p.block_revision, p.published_version_id, p.published_block_doc,
    COALESCE(
        json_agg(
            json_build_object(
                'id', m.id,
                'name', m.name,
                'description', m.description,
                'alt', m.alt,
                'media_path', m.media_path,
                'user_id', m.user_id,
                'created_at', m.created_at,
                'changed_at', m.changed_at,
                'order', pm."order"
            ) ORDER BY pm."order", m.created_at
        ) FILTER (WHERE m.id IS NOT NULL),
        '[]'::json
    ) as media
FROM posts p
LEFT JOIN post_media pm ON p.id = pm.post_id
LEFT JOIN media m ON pm.media_id = m.id
WHERE p.id = $1
GROUP BY p.id, p.title, p.description, p.published_block_doc, p.user_id, p.username, p.url, p.created_at, p.changed_at
`

type GetPostWithMediaRow struct {
	ID                 int64                 `json:"id"`
	Title              string                `json:"title"`
	Description        string                `json:"description"`
	UserID             int64                 `json:"user_id"`
	Username           string                `json:"username"`
	Url                string                `json:"url"`
	PostType           string                `json:"post_type"`
	PostStatus         string                `json:"post_status"`
	PostParent         sql.NullInt64         `json:"post_parent"`
	MenuOrder          int32                 `json:"menu_order"`
	CreatedAt          time.Time             `json:"created_at"`
	ChangedAt          time.Time             `json:"changed_at"`
	BlockDoc           json.RawMessage       `json:"block_doc"`
	BlockRevision      int64                 `json:"block_revision"`
	PublishedVersionID sql.NullInt64         `json:"published_version_id"`
	PublishedBlockDoc  pqtype.NullRawMessage `json:"published_block_doc"`
	Media              interface{}           `json:"media"`
}

func (q *Queries) GetPostWithMedia(ctx context.Context, id int64) (GetPostWithMediaRow, error) {
	row := q.db.QueryRowContext(ctx, getPostWithMedia, id)
	var i GetPostWithMediaRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.UserID,
		&i.Username,
		&i.Url,
		&i.PostType,
		&i.PostStatus,
		&i.PostParent,
		&i.MenuOrder,
		&i.CreatedAt,
		&i.ChangedAt,
		&i.BlockDoc,
		&i.BlockRevision,
		&i.PublishedVersionID,
		&i.PublishedBlockDoc,
		&i.Media,
	)
	return i, err
}

const getPostsByMedia = `-- name: GetPostsByMedia :many
SELECT 
    p.id, p.title, p.description, p.user_id, p.username, p.url, 
    p.post_type, p.post_status, p.post_parent, p.menu_order, p.created_at, p.changed_at,
    COALESCE(pm."order", 0) as media_order,
    CASE 
        WHEN pm.media_id IS NOT NULL AND pm."order" = 0 THEN 'featured'
        WHEN pm.media_id IS NOT NULL AND pm."order" > 0 THEN 'gallery'
        WHEN meta.meta_value IS NOT NULL THEN 'featured'
        ELSE 'unknown'
    END as relationship_type
FROM posts p
LEFT JOIN post_media pm ON p.id = pm.post_id AND pm.media_id = $1
LEFT JOIN post_meta meta ON p.id = meta.post_id 
    AND meta.meta_key = '_thumbnail_id' 
    AND meta.meta_value = $1::text
WHERE pm.media_id = $1 OR meta.meta_value = $1::text
ORDER BY 
    CASE WHEN pm."order" = 0 OR meta.meta_value IS NOT NULL THEN 0 ELSE 1 END,
    pm."order" ASC,
    p.created_at DESC
`

type GetPostsByMediaRow struct {
	ID               int64         `json:"id"`
	Title            string        `json:"title"`
	Description      string        `json:"description"`
	UserID           int64         `json:"user_id"`
	Username         string        `json:"username"`
	Url              string        `json:"url"`
	PostType         string        `json:"post_type"`
	PostStatus       string        `json:"post_status"`
	PostParent       sql.NullInt64 `json:"post_parent"`
	MenuOrder        int32         `json:"menu_order"`
	CreatedAt        time.Time     `json:"created_at"`
	ChangedAt        time.Time     `json:"changed_at"`
	MediaOrder       int32         `json:"media_order"`
	RelationshipType string        `json:"relationship_type"`
}

func (q *Queries) GetPostsByMedia(ctx context.Context, mediaID int64) ([]GetPostsByMediaRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsByMedia, mediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPostsByMediaRow{}
	for rows.Next() {
		var i GetPostsByMediaRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.UserID,
			&i.Username,
			&i.Url,
			&i.PostType,
			&i.PostStatus,
			&i.PostParent,
			&i.MenuOrder,
			&i.CreatedAt,
			&i.ChangedAt,
			&i.MediaOrder,
			&i.RelationshipType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsByUserWithMedia = `-- name: GetPostsByUserWithMedia :many
SELECT 
    p.id, p.title, p.description, p.user_id, p.username, p.url, p.post_type, p.post_status, p.post_parent, p.menu_order, p.created_at, p.changed_at, p.block_doc, p.block_revision, p.published_version_id, p.published_block_doc,
    COALESCE(
        json_agg(
            json_build_object(
                'id', m.id,
                'name', m.name,
                'description', m.description,
                'alt', m.alt,
                'media_path', m.media_path,
                'user_id', m.user_id,
                'created_at', m.created_at,
                'changed_at', m.changed_at,
                'order', pm."order"
            ) ORDER BY pm."order", m.created_at
        ) FILTER (WHERE m.id IS NOT NULL),
        '[]'::json
    ) as media
FROM posts p
LEFT JOIN post_media pm ON p.id = pm.post_id
LEFT JOIN media m ON pm.media_id = m.id
WHERE p.user_id = $1
GROUP BY p.id, p.title, p.description, p.published_block_doc, p.user_id, p.username, p.url, p.created_at, p.changed_at
ORDER BY p.created_at DESC
LIMIT $2
OFFSET $3
`

type GetPostsByUserWithMediaParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetPostsByUserWithMediaRow struct {
	ID                 int64                 `json:"id"`
	Title              string                `json:"title"`
	Description        string                `json:"description"`
	UserID             int64                 `json:"user_id"`
	Username           string                `json:"username"`
	Url                string                `json:"url"`
	PostType           string                `json:"post_type"`
	PostStatus         string                `json:"post_status"`
	PostParent         sql.NullInt64         `json:"post_parent"`
	MenuOrder          int32                 `json:"menu_order"`
	CreatedAt          time.Time             `json:"created_at"`
	ChangedAt          time.Time             `json:"changed_at"`
	BlockDoc           json.RawMessage       `json:"block_doc"`
	BlockRevision      int64                 `json:"block_revision"`
	PublishedVersionID sql.NullInt64         `json:"published_version_id"`
	PublishedBlockDoc  pqtype.NullRawMessage `json:"published_block_doc"`
	Media              interface{}           `json:"media"`
}

func (q *Queries) GetPostsByUserWithMedia(ctx context.Context, arg GetPostsByUserWithMediaParams) ([]GetPostsByUserWithMediaRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsByUserWithMedia, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPostsByUserWithMediaRow{}
	for rows.Next() {
		var i GetPostsByUserWithMediaRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.UserID,
			&i.Username,
			&i.Url,
			&i.PostType,
			&i.PostStatus,
			&i.PostParent,
			&i.MenuOrder,
			&i.CreatedAt,
			&i.ChangedAt,
			&i.BlockDoc,
			&i.BlockRevision,
			&i.PublishedVersionID,
			&i.PublishedBlockDoc,
			&i.Media,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserMediaCount = `-- name: GetUserMediaCount :one
SELECT COUNT(*) FROM media
WHERE user_id = $1
`

func (q *Queries) GetUserMediaCount(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserMediaCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listMedia = `-- name: ListMedia :many
SELECT 
    m.id, m.name, m.description, m.alt, m.media_path, m.user_id, m.created_at, m.changed_at, m.file_size, m.mime_type, m.width, m.height, m.duration, m.original_filename, m.metadata,
    COUNT(pm.post_id) as post_count
FROM media m
LEFT JOIN post_media pm ON m.id = pm.media_id
WHERE 
    ($1 = '' OR m.mime_type LIKE $1 || '%')
    AND ($2 = 0 OR m.user_id = $2)
    AND ($3 = '' OR (m.name ILIKE '%' || $3 || '%' OR m.description ILIKE '%' || $3 || '%'))
GROUP BY m.id, m.name, m.description, m.alt, m.media_path, m.user_id, m.created_at, m.changed_at, m.file_size, m.mime_type, m.width, m.height, m.duration, m.original_filename, m.metadata
ORDER BY 
    CASE WHEN $4 = 'date_asc' THEN m.created_at END ASC,
    CASE WHEN $4 = 'date_desc' THEN m.created_at END DESC,
    CASE WHEN $4 = 'name_asc' THEN m.name END ASC,
    CASE WHEN $4 = 'name_desc' THEN m.name END DESC,
    CASE WHEN $4 = 'size_asc' THEN m.file_size END ASC,
    CASE WHEN $4 = 'size_desc' THEN m.file_size END DESC,
    CASE WHEN $4 = 'type_asc' THEN m.mime_type END ASC,
    CASE WHEN $4 = 'type_desc' THEN m.mime_type END DESC,
    CASE WHEN $4 = 'posts_asc' THEN COUNT(pm.post_id) END ASC,
    CASE WHEN $4 = 'posts_desc' THEN COUNT(pm.post_id) END DESC,
    m.created_at DESC
LIMIT $5
OFFSET $6
`

type ListMediaParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Column4 interface{} `json:"column_4"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListMediaRow struct {
	ID               int64           `json:"id"`
	Name             string          `json:"name"`
	Description      string          `json:"description"`
	Alt              string          `json:"alt"`
	MediaPath        string          `json:"media_path"`
	UserID           int64           `json:"user_id"`
	CreatedAt        time.Time       `json:"created_at"`
	ChangedAt        time.Time       `json:"changed_at"`
	FileSize         int64           `json:"file_size"`
	MimeType         string          `json:"mime_type"`
	Width            int32           `json:"width"`
	Height           int32           `json:"height"`
	Duration         int32           `json:"duration"`
	OriginalFilename string          `json:"original_filename"`
	Metadata         json.RawMessage `json:"metadata"`
	PostCount        int64           `json:"post_count"`
}

func (q *Queries) ListMedia(ctx context.Context, arg ListMediaParams) ([]ListMediaRow, error) {
	rows, err := q.db.QueryContext(ctx, listMedia,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMediaRow{}
	for rows.Next() {
		var i ListMediaRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Alt,
			&i.MediaPath,
			&i.UserID,
			&i.CreatedAt,
			&i.ChangedAt,
			&i.FileSize,
			&i.MimeType,
			&i.Width,
			&i.Height,
			&i.Duration,
			&i.OriginalFilename,
			&i.Metadata,
			&i.PostCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsWithMedia = `-- name: ListPostsWithMedia :many
SELECT 
    p.id, p.title, p.description, p.user_id, p.username, p.url, p.post_type, p.post_status, p.post_parent, p.menu_order, p.created_at, p.changed_at, p.block_doc, p.block_revision, p.published_version_id, p.published_block_doc,
    COALESCE(
        json_agg(
            json_build_object(
                'id', m.id,
                'name', m.name,
                'description', m.description,
                'alt', m.alt,
                'media_path', m.media_path,
                'user_id', m.user_id,
                'created_at', m.created_at,
                'changed_at', m.changed_at,
                'order', pm."order"
            ) ORDER BY pm."order", m.created_at
        ) FILTER (WHERE m.id IS NOT NULL),
        '[]'::json
    ) as media
FROM posts p
LEFT JOIN post_media pm ON p.id = pm.post_id
LEFT JOIN media m ON pm.media_id = m.id
GROUP BY p.id, p.title, p.description, p.published_block_doc, p.user_id, p.username, p.url, p.created_at, p.changed_at
ORDER BY p.created_at DESC
LIMIT $1
OFFSET $2
`

type ListPostsWithMediaParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPostsWithMediaRow struct {
	ID                 int64                 `json:"id"`
	Title              string                `json:"title"`
	Description        string                `json:"description"`
	UserID             int64                 `json:"user_id"`
	Username           string                `json:"username"`
	Url                string                `json:"url"`
	PostType           string                `json:"post_type"`
	PostStatus         string                `json:"post_status"`
	PostParent         sql.NullInt64         `json:"post_parent"`
	MenuOrder          int32                 `json:"menu_order"`
	CreatedAt          time.Time             `json:"created_at"`
	ChangedAt          time.Time             `json:"changed_at"`
	BlockDoc           json.RawMessage       `json:"block_doc"`
	BlockRevision      int64                 `json:"block_revision"`
	PublishedVersionID sql.NullInt64         `json:"published_version_id"`
	PublishedBlockDoc  pqtype.NullRawMessage `json:"published_block_doc"`
	Media              interface{}           `json:"media"`
}

func (q *Queries) ListPostsWithMedia(ctx context.Context, arg ListPostsWithMediaParams) ([]ListPostsWithMediaRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostsWithMedia, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsWithMediaRow{}
	for rows.Next() {
		var i ListPostsWithMediaRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.UserID,
			&i.Username,
			&i.Url,
			&i.PostType,
			&i.PostStatus,
			&i.PostParent,
			&i.MenuOrder,
			&i.CreatedAt,
			&i.ChangedAt,
			&i.BlockDoc,
			&i.BlockRevision,
			&i.PublishedVersionID,
			&i.PublishedBlockDoc,
			&i.Media,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMediaByName = `-- name: SearchMediaByName :many
SELECT 
    m.id, m.name, m.description, m.alt, m.media_path, m.user_id, m.created_at, m.changed_at, m.file_size, m.mime_type, m.width, m.height, m.duration, m.original_filename, m.metadata,
    COUNT(pm.post_id) as post_count
FROM media m
LEFT JOIN post_media pm ON m.id = pm.media_id
WHERE 
    (m.name ILIKE '%' || $1 || '%' OR m.description ILIKE '%' || $1 || '%')
    AND ($2 = '' OR m.mime_type LIKE $2 || '%')
    AND ($3 = 0 OR m.user_id = $3)
GROUP BY m.id, m.name, m.description, m.alt, m.media_path, m.user_id, m.created_at, m.changed_at, m.file_size, m.mime_type, m.width, m.height, m.duration, m.original_filename, m.metadata
ORDER BY 
    CASE WHEN $4 = 'date_asc' THEN m.created_at END ASC,
    CASE WHEN $4 = 'date_desc' THEN m.created_at END DESC,
    CASE WHEN $4 = 'name_asc' THEN m.name END ASC,
    CASE WHEN $4 = 'name_desc' THEN m.name END DESC,
    CASE WHEN $4 = 'size_asc' THEN m.file_size END ASC,
    CASE WHEN $4 = 'size_desc' THEN m.file_size END DESC,
    CASE WHEN $4 = 'type_asc' THEN m.mime_type END ASC,
    CASE WHEN $4 = 'type_desc' THEN m.mime_type END DESC,
    CASE WHEN $4 = 'posts_asc' THEN COUNT(pm.post_id) END ASC,
    CASE WHEN $4 = 'posts_desc' THEN COUNT(pm.post_id) END DESC,
    m.created_at DESC
LIMIT $5
OFFSET $6
`

type SearchMediaByNameParams struct {
	Column1 sql.NullString `json:"column_1"`
	Column2 interface{}    `json:"column_2"`
	Column3 interface{}    `json:"column_3"`
	Column4 interface{}    `json:"column_4"`
	Limit   int32          `json:"limit"`
	Offset  int32          `json:"offset"`
}

type SearchMediaByNameRow struct {
	ID               int64           `json:"id"`
	Name             string          `json:"name"`
	Description      string          `json:"description"`
	Alt              string          `json:"alt"`
	MediaPath        string          `json:"media_path"`
	UserID           int64           `json:"user_id"`
	CreatedAt        time.Time       `json:"created_at"`
	ChangedAt        time.Time       `json:"changed_at"`
	FileSize         int64           `json:"file_size"`
	MimeType         string          `json:"mime_type"`
	Width            int32           `json:"width"`
	Height           int32           `json:"height"`
	Duration         int32           `json:"duration"`
	OriginalFilename string          `json:"original_filename"`
	Metadata         json.RawMessage `json:"metadata"`
	PostCount        int64           `json:"post_count"`
}

func (q *Queries) SearchMediaByName(ctx context.Context, arg SearchMediaByNameParams) ([]SearchMediaByNameRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMediaByName,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMediaByNameRow{}
	for rows.Next() {
		var i SearchMediaByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Alt,
			&i.MediaPath,
			&i.UserID,
			&i.CreatedAt,
			&i.ChangedAt,
			&i.FileSize,
			&i.MimeType,
			&i.Width,
			&i.Height,
			&i.Duration,
			&i.OriginalFilename,
			&i.Metadata,
			&i.PostCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transferMediaToUser = `-- name: TransferMediaToUser :exec
UPDATE media
SET user_id = $2
WHERE user_id = $1
`

type TransferMediaToUserParams struct {
	UserID   int64 `json:"user_id"`
	UserID_2 int64 `json:"user_id_2"`
}

func (q *Queries) TransferMediaToUser(ctx context.Context, arg TransferMediaToUserParams) error {
	_, err := q.db.ExecContext(ctx, transferMediaToUser, arg.UserID, arg.UserID_2)
	return err
}

const updateMedia = `-- name: UpdateMedia :one
UPDATE media
SET
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    alt = COALESCE($4, alt),
    media_path = COALESCE($5, media_path),
    file_size = COALESCE($6, file_size),
    mime_type = COALESCE($7, mime_type),
    width = COALESCE($8, width),
    height = COALESCE($9, height),
    duration = COALESCE($10, duration),
    original_filename = COALESCE($11, original_filename),
    changed_at = now()
WHERE id = $1
RETURNING id, name, description, alt, media_path, user_id, created_at, changed_at, file_size, mime_type, width, height, duration, original_filename, metadata
`

type UpdateMediaParams struct {
	ID               int64  `json:"id"`
	Name             string `json:"name"`
	Description      string `json:"description"`
	Alt              string `json:"alt"`
	MediaPath        string `json:"media_path"`
	FileSize         int64  `json:"file_size"`
	MimeType         string `json:"mime_type"`
	Width            int32  `json:"width"`
	Height           int32  `json:"height"`
	Duration         int32  `json:"duration"`
	OriginalFilename string `json:"original_filename"`
}

func (q *Queries) UpdateMedia(ctx context.Context, arg UpdateMediaParams) (Medium, error) {
	row := q.db.QueryRowContext(ctx, updateMedia,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Alt,
		arg.MediaPath,
		arg.FileSize,
		arg.MimeType,
		arg.Width,
		arg.Height,
		arg.Duration,
		arg.OriginalFilename,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Alt,
		&i.MediaPath,
		&i.UserID,
		&i.CreatedAt,
		&i.ChangedAt,
		&i.FileSize,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.Duration,
		&i.OriginalFilename,
		&i.Metadata,
	)
	return i, err
}
