// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Medium struct {
	ID               int64           `json:"id"`
	Name             string          `json:"name"`
	Description      string          `json:"description"`
	Alt              string          `json:"alt"`
	MediaPath        string          `json:"media_path"`
	UserID           int64           `json:"user_id"`
	CreatedAt        time.Time       `json:"created_at"`
	ChangedAt        time.Time       `json:"changed_at"`
	FileSize         int64           `json:"file_size"`
	MimeType         string          `json:"mime_type"`
	Width            int32           `json:"width"`
	Height           int32           `json:"height"`
	Duration         int32           `json:"duration"`
	OriginalFilename string          `json:"original_filename"`
	Metadata         json.RawMessage `json:"metadata"`
}

type Post struct {
	ID          int64         `json:"id"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	Content     string        `json:"content"`
	UserID      int64         `json:"user_id"`
	Username    string        `json:"username"`
	Url         string        `json:"url"`
	PostType    string        `json:"post_type"`
	PostStatus  string        `json:"post_status"`
	PostParent  sql.NullInt64 `json:"post_parent"`
	MenuOrder   int32         `json:"menu_order"`
	CreatedAt   time.Time     `json:"created_at"`
	ChangedAt   time.Time     `json:"changed_at"`
}

type PostMedium struct {
	PostID  int64 `json:"post_id"`
	MediaID int64 `json:"media_id"`
	Order   int32 `json:"order"`
}

type PostMetum struct {
	ID        int64          `json:"id"`
	PostID    int64          `json:"post_id"`
	MetaKey   string         `json:"meta_key"`
	MetaValue sql.NullString `json:"meta_value"`
	CreatedAt time.Time      `json:"created_at"`
}

type PostTaxonomyRelationship struct {
	PostID         int64     `json:"post_id"`
	TaxonomyTermID int64     `json:"taxonomy_term_id"`
	CreatedAt      time.Time `json:"created_at"`
}

type PostType struct {
	ID           int64           `json:"id"`
	Name         string          `json:"name"`
	Label        string          `json:"label"`
	Description  sql.NullString  `json:"description"`
	Public       bool            `json:"public"`
	Hierarchical bool            `json:"hierarchical"`
	HasArchive   bool            `json:"has_archive"`
	MenuPosition sql.NullInt32   `json:"menu_position"`
	Supports     json.RawMessage `json:"supports"`
	CreatedAt    time.Time       `json:"created_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	UserID       int64     `json:"user_id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type TaxonomyTerm struct {
	ID             int64                 `json:"id"`
	Name           string                `json:"name"`
	Slug           string                `json:"slug"`
	Description    sql.NullString        `json:"description"`
	ParentID       sql.NullInt64         `json:"parent_id"`
	TaxonomyTypeID int64                 `json:"taxonomy_type_id"`
	SortOrder      sql.NullInt32         `json:"sort_order"`
	Meta           pqtype.NullRawMessage `json:"meta"`
	CreatedAt      time.Time             `json:"created_at"`
}

type TaxonomyType struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Label        string         `json:"label"`
	Description  sql.NullString `json:"description"`
	Hierarchical bool           `json:"hierarchical"`
	Public       bool           `json:"public"`
	ShowUi       bool           `json:"show_ui"`
	ShowInMenu   bool           `json:"show_in_menu"`
	CreatedAt    time.Time      `json:"created_at"`
}

type User struct {
	ID                int64     `json:"id"`
	Username          string    `json:"username"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	HashedPassword    string    `json:"hashed_password"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
	Role              string    `json:"role"`
}

type UserPost struct {
	PostID int64 `json:"post_id"`
	UserID int64 `json:"user_id"`
	Order  int32 `json:"order"`
}
