// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: post_blocks.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/sqlc-dev/pqtype"
)

const getPostBlocks = `-- name: GetPostBlocks :one
SELECT block_doc AS content, block_revision AS revision
FROM posts
WHERE id = $1
`

type GetPostBlocksRow struct {
	Content  json.RawMessage `json:"content"`
	Revision int64           `json:"revision"`
}

func (q *Queries) GetPostBlocks(ctx context.Context, id int64) (GetPostBlocksRow, error) {
	row := q.db.QueryRowContext(ctx, getPostBlocks, id)
	var i GetPostBlocksRow
	err := row.Scan(&i.Content, &i.Revision)
	return i, err
}

const getPublishedPostBlocks = `-- name: GetPublishedPostBlocks :one
SELECT published_block_doc AS content
FROM posts
WHERE id = $1
`

func (q *Queries) GetPublishedPostBlocks(ctx context.Context, id int64) (pqtype.NullRawMessage, error) {
	row := q.db.QueryRowContext(ctx, getPublishedPostBlocks, id)
	var content pqtype.NullRawMessage
	err := row.Scan(&content)
	return content, err
}

const updatePostBlocksIfRevisionMatches = `-- name: UpdatePostBlocksIfRevisionMatches :one
UPDATE posts
SET block_doc = $2,
    block_revision = block_revision + 1
WHERE id = $1
  AND block_revision = $3
RETURNING block_doc AS content, block_revision AS revision
`

type UpdatePostBlocksIfRevisionMatchesParams struct {
	ID            int64           `json:"id"`
	BlockDoc      json.RawMessage `json:"block_doc"`
	BlockRevision int64           `json:"block_revision"`
}

type UpdatePostBlocksIfRevisionMatchesRow struct {
	Content  json.RawMessage `json:"content"`
	Revision int64           `json:"revision"`
}

func (q *Queries) UpdatePostBlocksIfRevisionMatches(ctx context.Context, arg UpdatePostBlocksIfRevisionMatchesParams) (UpdatePostBlocksIfRevisionMatchesRow, error) {
	row := q.db.QueryRowContext(ctx, updatePostBlocksIfRevisionMatches, arg.ID, arg.BlockDoc, arg.BlockRevision)
	var i UpdatePostBlocksIfRevisionMatchesRow
	err := row.Scan(&i.Content, &i.Revision)
	return i, err
}
