// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: post_versions.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const getLatestPublishedVersion = `-- name: GetLatestPublishedVersion :one
SELECT id, version_no, status, label, message, block_doc, created_at, created_by
FROM post_versions
WHERE post_id = $1
  AND status = 'published'
ORDER BY version_no DESC
LIMIT 1
`

type GetLatestPublishedVersionRow struct {
	ID        int64           `json:"id"`
	VersionNo int32           `json:"version_no"`
	Status    string          `json:"status"`
	Label     sql.NullString  `json:"label"`
	Message   sql.NullString  `json:"message"`
	BlockDoc  json.RawMessage `json:"block_doc"`
	CreatedAt time.Time       `json:"created_at"`
	CreatedBy sql.NullInt64   `json:"created_by"`
}

func (q *Queries) GetLatestPublishedVersion(ctx context.Context, postID int64) (GetLatestPublishedVersionRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestPublishedVersion, postID)
	var i GetLatestPublishedVersionRow
	err := row.Scan(
		&i.ID,
		&i.VersionNo,
		&i.Status,
		&i.Label,
		&i.Message,
		&i.BlockDoc,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getNextVersionNoForPost = `-- name: GetNextVersionNoForPost :one
SELECT COALESCE(MAX(version_no), 0) + 1 AS next_no
FROM post_versions
WHERE post_id = $1
`

func (q *Queries) GetNextVersionNoForPost(ctx context.Context, postID int64) (int32, error) {
	row := q.db.QueryRowContext(ctx, getNextVersionNoForPost, postID)
	var next_no int32
	err := row.Scan(&next_no)
	return next_no, err
}

const getPostVersions = `-- name: GetPostVersions :many
SELECT id, version_no, status, label, message, created_at, created_by
FROM post_versions
WHERE post_id = $1
ORDER BY version_no DESC
`

type GetPostVersionsRow struct {
	ID        int64          `json:"id"`
	VersionNo int32          `json:"version_no"`
	Status    string         `json:"status"`
	Label     sql.NullString `json:"label"`
	Message   sql.NullString `json:"message"`
	CreatedAt time.Time      `json:"created_at"`
	CreatedBy sql.NullInt64  `json:"created_by"`
}

func (q *Queries) GetPostVersions(ctx context.Context, postID int64) ([]GetPostVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostVersions, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPostVersionsRow{}
	for rows.Next() {
		var i GetPostVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.VersionNo,
			&i.Status,
			&i.Label,
			&i.Message,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPostVersion = `-- name: InsertPostVersion :one
INSERT INTO post_versions (post_id, version_no, status, label, message, block_doc, created_by)
VALUES ($1, $2, 'published', $3, $4, $5, $6)
RETURNING id, version_no
`

type InsertPostVersionParams struct {
	PostID    int64           `json:"post_id"`
	VersionNo int32           `json:"version_no"`
	Label     sql.NullString  `json:"label"`
	Message   sql.NullString  `json:"message"`
	BlockDoc  json.RawMessage `json:"block_doc"`
	CreatedBy sql.NullInt64   `json:"created_by"`
}

type InsertPostVersionRow struct {
	ID        int64 `json:"id"`
	VersionNo int32 `json:"version_no"`
}

func (q *Queries) InsertPostVersion(ctx context.Context, arg InsertPostVersionParams) (InsertPostVersionRow, error) {
	row := q.db.QueryRowContext(ctx, insertPostVersion,
		arg.PostID,
		arg.VersionNo,
		arg.Label,
		arg.Message,
		arg.BlockDoc,
		arg.CreatedBy,
	)
	var i InsertPostVersionRow
	err := row.Scan(&i.ID, &i.VersionNo)
	return i, err
}

const setPublishedVersionOnPost = `-- name: SetPublishedVersionOnPost :exec
UPDATE posts
SET published_version_id = $2,
    published_block_doc = $3
WHERE id = $1
`

type SetPublishedVersionOnPostParams struct {
	ID                 int64                 `json:"id"`
	PublishedVersionID sql.NullInt64         `json:"published_version_id"`
	PublishedBlockDoc  pqtype.NullRawMessage `json:"published_block_doc"`
}

func (q *Queries) SetPublishedVersionOnPost(ctx context.Context, arg SetPublishedVersionOnPostParams) error {
	_, err := q.db.ExecContext(ctx, setPublishedVersionOnPost, arg.ID, arg.PublishedVersionID, arg.PublishedBlockDoc)
	return err
}
