// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: post.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const countFilteredPosts = `-- name: CountFilteredPosts :one
SELECT COUNT(*) AS total FROM posts
WHERE 
    ($1::text = '' OR post_type = $1)
    AND ($2::text = '' OR post_status = $2)
`

type CountFilteredPostsParams struct {
	PostType   string `json:"post_type"`
	PostStatus string `json:"post_status"`
}

func (q *Queries) CountFilteredPosts(ctx context.Context, arg CountFilteredPostsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFilteredPosts, arg.PostType, arg.PostStatus)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countPostsByType = `-- name: CountPostsByType :one
SELECT COUNT(*) AS total FROM posts
WHERE post_type = $1
`

func (q *Queries) CountPostsByType(ctx context.Context, postType string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPostsByType, postType)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countPostsByTypeFiltered = `-- name: CountPostsByTypeFiltered :one
SELECT COUNT(*) AS total FROM posts
WHERE post_type = $1
    AND ($2::text = '' OR post_status = $2)
`

type CountPostsByTypeFilteredParams struct {
	PostType   string `json:"post_type"`
	PostStatus string `json:"post_status"`
}

func (q *Queries) CountPostsByTypeFiltered(ctx context.Context, arg CountPostsByTypeFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPostsByTypeFiltered, arg.PostType, arg.PostStatus)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countTotalPosts = `-- name: CountTotalPosts :one
SELECT COUNT(*) AS total FROM posts
`

func (q *Queries) CountTotalPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTotalPosts)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createPosts = `-- name: CreatePosts :one
INSERT INTO posts (
    title,
    description,
    user_id,
    username,
    content,
    url,
    post_type,
    post_status,
    post_parent,
    menu_order
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, title, description, content, user_id, username, url, post_type, post_status, post_parent, menu_order, created_at, changed_at
`

type CreatePostsParams struct {
	Title       string        `json:"title"`
	Description string        `json:"description"`
	UserID      int64         `json:"user_id"`
	Username    string        `json:"username"`
	Content     string        `json:"content"`
	Url         string        `json:"url"`
	PostType    string        `json:"post_type"`
	PostStatus  string        `json:"post_status"`
	PostParent  sql.NullInt64 `json:"post_parent"`
	MenuOrder   int32         `json:"menu_order"`
}

func (q *Queries) CreatePosts(ctx context.Context, arg CreatePostsParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPosts,
		arg.Title,
		arg.Description,
		arg.UserID,
		arg.Username,
		arg.Content,
		arg.Url,
		arg.PostType,
		arg.PostStatus,
		arg.PostParent,
		arg.MenuOrder,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Content,
		&i.UserID,
		&i.Username,
		&i.Url,
		&i.PostType,
		&i.PostStatus,
		&i.PostParent,
		&i.MenuOrder,
		&i.CreatedAt,
		&i.ChangedAt,
	)
	return i, err
}

const createUserPost = `-- name: CreateUserPost :one
INSERT INTO user_posts (
    post_id,
    user_id,
    "order"
) VALUES (
    $1, $2, $3
) RETURNING post_id, user_id, "order"
`

type CreateUserPostParams struct {
	PostID int64 `json:"post_id"`
	UserID int64 `json:"user_id"`
	Order  int32 `json:"order"`
}

func (q *Queries) CreateUserPost(ctx context.Context, arg CreateUserPostParams) (UserPost, error) {
	row := q.db.QueryRowContext(ctx, createUserPost, arg.PostID, arg.UserID, arg.Order)
	var i UserPost
	err := row.Scan(&i.PostID, &i.UserID, &i.Order)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts
WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePost, id)
	return err
}

const deleteUserPost = `-- name: DeleteUserPost :exec
DELETE FROM user_posts
WHERE post_id = $1
`

func (q *Queries) DeleteUserPost(ctx context.Context, postID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserPost, postID)
	return err
}

const getPost = `-- name: GetPost :one
SELECT id, title, description, content, user_id, username, url, post_type, post_status, post_parent, menu_order, created_at, changed_at FROM posts 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPost(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Content,
		&i.UserID,
		&i.Username,
		&i.Url,
		&i.PostType,
		&i.PostStatus,
		&i.PostParent,
		&i.MenuOrder,
		&i.CreatedAt,
		&i.ChangedAt,
	)
	return i, err
}

const getPostChildren = `-- name: GetPostChildren :many
SELECT id, title, description, content, user_id, username, url, post_type, post_status, post_parent, menu_order, created_at, changed_at FROM posts
WHERE post_parent = $1
ORDER BY menu_order ASC, title ASC
`

func (q *Queries) GetPostChildren(ctx context.Context, postParent sql.NullInt64) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPostChildren, postParent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.UserID,
			&i.Username,
			&i.Url,
			&i.PostType,
			&i.PostStatus,
			&i.PostParent,
			&i.MenuOrder,
			&i.CreatedAt,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostWithMeta = `-- name: GetPostWithMeta :one
SELECT 
    p.id, p.title, p.description, p.content, p.user_id, p.username, p.url, p.post_type, p.post_status, p.post_parent, p.menu_order, p.created_at, p.changed_at,
    COALESCE(
        jsonb_object_agg(
            pm.meta_key, 
            pm.meta_value
        ) FILTER (WHERE pm.meta_key IS NOT NULL),
        '{}'::jsonb
    ) as meta
FROM posts p
LEFT JOIN post_meta pm ON p.id = pm.post_id
WHERE p.id = $1
GROUP BY p.id, p.title, p.description, p.content, p.user_id, p.username, p.url, p.post_type, p.post_status, p.post_parent, p.menu_order, p.created_at, p.changed_at
`

type GetPostWithMetaRow struct {
	ID          int64         `json:"id"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	Content     string        `json:"content"`
	UserID      int64         `json:"user_id"`
	Username    string        `json:"username"`
	Url         string        `json:"url"`
	PostType    string        `json:"post_type"`
	PostStatus  string        `json:"post_status"`
	PostParent  sql.NullInt64 `json:"post_parent"`
	MenuOrder   int32         `json:"menu_order"`
	CreatedAt   time.Time     `json:"created_at"`
	ChangedAt   time.Time     `json:"changed_at"`
	Meta        interface{}   `json:"meta"`
}

func (q *Queries) GetPostWithMeta(ctx context.Context, id int64) (GetPostWithMetaRow, error) {
	row := q.db.QueryRowContext(ctx, getPostWithMeta, id)
	var i GetPostWithMetaRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Content,
		&i.UserID,
		&i.Username,
		&i.Url,
		&i.PostType,
		&i.PostStatus,
		&i.PostParent,
		&i.MenuOrder,
		&i.CreatedAt,
		&i.ChangedAt,
		&i.Meta,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT id, title, description, content, user_id, username, url, post_type, post_status, post_parent, menu_order, created_at, changed_at FROM posts
WHERE 
    ($1 = '' OR post_type = $1)
    AND ($2 = '' OR post_status = $2)
ORDER BY
    CASE WHEN $3 = 'date_asc' THEN created_at END ASC,
    CASE WHEN $3 = 'date_desc' THEN created_at END DESC,
    CASE WHEN $3 = 'title_asc' THEN title END ASC,
    CASE WHEN $3 = 'title_desc' THEN title END DESC,
    CASE WHEN $3 = 'menu_order_asc' THEN menu_order END ASC,
    CASE WHEN $3 = 'menu_order_desc' THEN menu_order END DESC,
    CASE WHEN $3 = 'id_asc' THEN id END ASC,
    CASE WHEN $3 = 'id_desc' THEN id END DESC,
    id DESC
LIMIT $5
OFFSET $4
`

type ListPostsParams struct {
	Column1     interface{} `json:"column_1"`
	Column2     interface{} `json:"column_2"`
	SortBy      interface{} `json:"sort_by"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPosts,
		arg.Column1,
		arg.Column2,
		arg.SortBy,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.UserID,
			&i.Username,
			&i.Url,
			&i.PostType,
			&i.PostStatus,
			&i.PostParent,
			&i.MenuOrder,
			&i.CreatedAt,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByType = `-- name: ListPostsByType :many
SELECT id, title, description, content, user_id, username, url, post_type, post_status, post_parent, menu_order, created_at, changed_at FROM posts
WHERE post_type = $1
    AND ($2 = '' OR post_status = $2)
ORDER BY
    CASE WHEN $3 = 'date_asc' THEN created_at END ASC,
    CASE WHEN $3 = 'date_desc' THEN created_at END DESC,
    CASE WHEN $3 = 'title_asc' THEN title END ASC,
    CASE WHEN $3 = 'title_desc' THEN title END DESC,
    CASE WHEN $3 = 'menu_order_asc' THEN menu_order END ASC,
    CASE WHEN $3 = 'menu_order_desc' THEN menu_order END DESC,
    id DESC
LIMIT $5
OFFSET $4
`

type ListPostsByTypeParams struct {
	PostType    string      `json:"post_type"`
	Column2     interface{} `json:"column_2"`
	SortBy      interface{} `json:"sort_by"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

func (q *Queries) ListPostsByType(ctx context.Context, arg ListPostsByTypeParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPostsByType,
		arg.PostType,
		arg.Column2,
		arg.SortBy,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.UserID,
			&i.Username,
			&i.Url,
			&i.PostType,
			&i.PostStatus,
			&i.PostParent,
			&i.MenuOrder,
			&i.CreatedAt,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByTypeWithAllMeta = `-- name: ListPostsByTypeWithAllMeta :many
SELECT 
    p.id, p.title, p.description, p.content, p.user_id, p.username, p.url, 
    p.post_type, p.post_status, p.post_parent, p.menu_order, p.created_at, p.changed_at,
    -- Post custom meta
    COALESCE(
        jsonb_object_agg(
            pm.meta_key, 
            pm.meta_value
        ) FILTER (WHERE pm.meta_key IS NOT NULL),
        '{}'::jsonb
    ) as post_meta,
    -- Author information
    jsonb_build_object(
        'id', u.id,
        'username', u.username,
        'email', u.email,
        'full_name', u.full_name,
        'role', u.role,
        'created_at', u.created_at
    ) as author_meta,
    -- Post type information
    jsonb_build_object(
        'name', pt.name,
        'label', pt.label,
        'description', pt.description,
        'hierarchical', pt.hierarchical,
        'public', pt.public,
        'supports', pt.supports
    ) as post_type_meta
FROM posts p
LEFT JOIN post_meta pm ON p.id = pm.post_id
LEFT JOIN users u ON p.user_id = u.id
LEFT JOIN post_types pt ON p.post_type = pt.name
WHERE p.post_type = $1
    AND ($2 = '' OR p.post_status = $2)
GROUP BY p.id, p.title, p.description, p.content, p.user_id, p.username, p.url, 
         p.post_type, p.post_status, p.post_parent, p.menu_order, p.created_at, p.changed_at,
         u.id, u.username, u.email, u.full_name, u.role, u.created_at,
         pt.name, pt.label, pt.description, pt.hierarchical, pt.public, pt.supports
ORDER BY
    CASE WHEN $3 = 'date_asc' THEN p.created_at END ASC,
    CASE WHEN $3 = 'date_desc' THEN p.created_at END DESC,
    CASE WHEN $3 = 'title_asc' THEN p.title END ASC,
    CASE WHEN $3 = 'title_desc' THEN p.title END DESC,
    CASE WHEN $3 = 'menu_order_asc' THEN p.menu_order END ASC,
    CASE WHEN $3 = 'menu_order_desc' THEN p.menu_order END DESC,
    p.id DESC
LIMIT $5
OFFSET $4
`

type ListPostsByTypeWithAllMetaParams struct {
	PostType    string      `json:"post_type"`
	Column2     interface{} `json:"column_2"`
	SortBy      interface{} `json:"sort_by"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

type ListPostsByTypeWithAllMetaRow struct {
	ID           int64           `json:"id"`
	Title        string          `json:"title"`
	Description  string          `json:"description"`
	Content      string          `json:"content"`
	UserID       int64           `json:"user_id"`
	Username     string          `json:"username"`
	Url          string          `json:"url"`
	PostType     string          `json:"post_type"`
	PostStatus   string          `json:"post_status"`
	PostParent   sql.NullInt64   `json:"post_parent"`
	MenuOrder    int32           `json:"menu_order"`
	CreatedAt    time.Time       `json:"created_at"`
	ChangedAt    time.Time       `json:"changed_at"`
	PostMeta     interface{}     `json:"post_meta"`
	AuthorMeta   json.RawMessage `json:"author_meta"`
	PostTypeMeta json.RawMessage `json:"post_type_meta"`
}

func (q *Queries) ListPostsByTypeWithAllMeta(ctx context.Context, arg ListPostsByTypeWithAllMetaParams) ([]ListPostsByTypeWithAllMetaRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostsByTypeWithAllMeta,
		arg.PostType,
		arg.Column2,
		arg.SortBy,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsByTypeWithAllMetaRow{}
	for rows.Next() {
		var i ListPostsByTypeWithAllMetaRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.UserID,
			&i.Username,
			&i.Url,
			&i.PostType,
			&i.PostStatus,
			&i.PostParent,
			&i.MenuOrder,
			&i.CreatedAt,
			&i.ChangedAt,
			&i.PostMeta,
			&i.AuthorMeta,
			&i.PostTypeMeta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByTypeWithMeta = `-- name: ListPostsByTypeWithMeta :many
SELECT 
    p.id, p.title, p.description, p.content, p.user_id, p.username, p.url, 
    p.post_type, p.post_status, p.post_parent, p.menu_order, p.created_at, p.changed_at,
    COALESCE(
        jsonb_object_agg(
            pm.meta_key, 
            pm.meta_value
        ) FILTER (WHERE pm.meta_key IS NOT NULL),
        '{}'::jsonb
    ) as meta
FROM posts p
LEFT JOIN post_meta pm ON p.id = pm.post_id
WHERE p.post_type = $1
    AND ($2 = '' OR p.post_status = $2)
GROUP BY p.id, p.title, p.description, p.content, p.user_id, p.username, p.url, p.post_type, p.post_status, p.post_parent, p.menu_order, p.created_at, p.changed_at
ORDER BY
    CASE WHEN $3 = 'date_asc' THEN p.created_at END ASC,
    CASE WHEN $3 = 'date_desc' THEN p.created_at END DESC,
    CASE WHEN $3 = 'title_asc' THEN p.title END ASC,
    CASE WHEN $3 = 'title_desc' THEN p.title END DESC,
    CASE WHEN $3 = 'menu_order_asc' THEN p.menu_order END ASC,
    CASE WHEN $3 = 'menu_order_desc' THEN p.menu_order END DESC,
    p.id DESC
LIMIT $5
OFFSET $4
`

type ListPostsByTypeWithMetaParams struct {
	PostType    string      `json:"post_type"`
	Column2     interface{} `json:"column_2"`
	SortBy      interface{} `json:"sort_by"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

type ListPostsByTypeWithMetaRow struct {
	ID          int64         `json:"id"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	Content     string        `json:"content"`
	UserID      int64         `json:"user_id"`
	Username    string        `json:"username"`
	Url         string        `json:"url"`
	PostType    string        `json:"post_type"`
	PostStatus  string        `json:"post_status"`
	PostParent  sql.NullInt64 `json:"post_parent"`
	MenuOrder   int32         `json:"menu_order"`
	CreatedAt   time.Time     `json:"created_at"`
	ChangedAt   time.Time     `json:"changed_at"`
	Meta        interface{}   `json:"meta"`
}

func (q *Queries) ListPostsByTypeWithMeta(ctx context.Context, arg ListPostsByTypeWithMetaParams) ([]ListPostsByTypeWithMetaRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostsByTypeWithMeta,
		arg.PostType,
		arg.Column2,
		arg.SortBy,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsByTypeWithMetaRow{}
	for rows.Next() {
		var i ListPostsByTypeWithMetaRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.UserID,
			&i.Username,
			&i.Url,
			&i.PostType,
			&i.PostStatus,
			&i.PostParent,
			&i.MenuOrder,
			&i.CreatedAt,
			&i.ChangedAt,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsWithAllMeta = `-- name: ListPostsWithAllMeta :many
SELECT 
    p.id, p.title, p.description, p.content, p.user_id, p.username, p.url, 
    p.post_type, p.post_status, p.post_parent, p.menu_order, p.created_at, p.changed_at,
    -- Post custom meta
    COALESCE(
        jsonb_object_agg(
            pm.meta_key, 
            pm.meta_value
        ) FILTER (WHERE pm.meta_key IS NOT NULL),
        '{}'::jsonb
    ) as post_meta,
    -- Author information
    jsonb_build_object(
        'id', u.id,
        'username', u.username,
        'email', u.email,
        'full_name', u.full_name,
        'role', u.role,
        'created_at', u.created_at
    ) as author_meta,
    -- Post type information
    jsonb_build_object(
        'name', pt.name,
        'label', pt.label,
        'description', pt.description,
        'hierarchical', pt.hierarchical,
        'public', pt.public,
        'supports', pt.supports
    ) as post_type_meta
FROM posts p
LEFT JOIN post_meta pm ON p.id = pm.post_id
LEFT JOIN users u ON p.user_id = u.id
LEFT JOIN post_types pt ON p.post_type = pt.name
WHERE 
    ($1 = '' OR p.post_type = $1)
    AND ($2 = '' OR p.post_status = $2)
GROUP BY p.id, p.title, p.description, p.content, p.user_id, p.username, p.url, 
         p.post_type, p.post_status, p.post_parent, p.menu_order, p.created_at, p.changed_at,
         u.id, u.username, u.email, u.full_name, u.role, u.created_at,
         pt.name, pt.label, pt.description, pt.hierarchical, pt.public, pt.supports
ORDER BY
    CASE WHEN $3 = 'date_asc' THEN p.created_at END ASC,
    CASE WHEN $3 = 'date_desc' THEN p.created_at END DESC,
    CASE WHEN $3 = 'title_asc' THEN p.title END ASC,
    CASE WHEN $3 = 'title_desc' THEN p.title END DESC,
    CASE WHEN $3 = 'menu_order_asc' THEN p.menu_order END ASC,
    CASE WHEN $3 = 'menu_order_desc' THEN p.menu_order END DESC,
    CASE WHEN $3 = 'id_asc' THEN p.id END ASC,
    CASE WHEN $3 = 'id_desc' THEN p.id END DESC,
    p.id DESC
LIMIT $5
OFFSET $4
`

type ListPostsWithAllMetaParams struct {
	Column1     interface{} `json:"column_1"`
	Column2     interface{} `json:"column_2"`
	SortBy      interface{} `json:"sort_by"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

type ListPostsWithAllMetaRow struct {
	ID           int64           `json:"id"`
	Title        string          `json:"title"`
	Description  string          `json:"description"`
	Content      string          `json:"content"`
	UserID       int64           `json:"user_id"`
	Username     string          `json:"username"`
	Url          string          `json:"url"`
	PostType     string          `json:"post_type"`
	PostStatus   string          `json:"post_status"`
	PostParent   sql.NullInt64   `json:"post_parent"`
	MenuOrder    int32           `json:"menu_order"`
	CreatedAt    time.Time       `json:"created_at"`
	ChangedAt    time.Time       `json:"changed_at"`
	PostMeta     interface{}     `json:"post_meta"`
	AuthorMeta   json.RawMessage `json:"author_meta"`
	PostTypeMeta json.RawMessage `json:"post_type_meta"`
}

func (q *Queries) ListPostsWithAllMeta(ctx context.Context, arg ListPostsWithAllMetaParams) ([]ListPostsWithAllMetaRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostsWithAllMeta,
		arg.Column1,
		arg.Column2,
		arg.SortBy,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsWithAllMetaRow{}
	for rows.Next() {
		var i ListPostsWithAllMetaRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.UserID,
			&i.Username,
			&i.Url,
			&i.PostType,
			&i.PostStatus,
			&i.PostParent,
			&i.MenuOrder,
			&i.CreatedAt,
			&i.ChangedAt,
			&i.PostMeta,
			&i.AuthorMeta,
			&i.PostTypeMeta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsWithMeta = `-- name: ListPostsWithMeta :many
SELECT 
    p.id, p.title, p.description, p.content, p.user_id, p.username, p.url, 
    p.post_type, p.post_status, p.post_parent, p.menu_order, p.created_at, p.changed_at,
    COALESCE(
        jsonb_object_agg(
            pm.meta_key, 
            pm.meta_value
        ) FILTER (WHERE pm.meta_key IS NOT NULL),
        '{}'::jsonb
    ) as meta
FROM posts p
LEFT JOIN post_meta pm ON p.id = pm.post_id
WHERE 
    ($1 = '' OR p.post_type = $1)
    AND ($2 = '' OR p.post_status = $2)
GROUP BY p.id, p.title, p.description, p.content, p.user_id, p.username, p.url, p.post_type, p.post_status, p.post_parent, p.menu_order, p.created_at, p.changed_at
ORDER BY
    CASE WHEN $3 = 'date_asc' THEN p.created_at END ASC,
    CASE WHEN $3 = 'date_desc' THEN p.created_at END DESC,
    CASE WHEN $3 = 'title_asc' THEN p.title END ASC,
    CASE WHEN $3 = 'title_desc' THEN p.title END DESC,
    CASE WHEN $3 = 'menu_order_asc' THEN p.menu_order END ASC,
    CASE WHEN $3 = 'menu_order_desc' THEN p.menu_order END DESC,
    CASE WHEN $3 = 'id_asc' THEN p.id END ASC,
    CASE WHEN $3 = 'id_desc' THEN p.id END DESC,
    p.id DESC
LIMIT $5
OFFSET $4
`

type ListPostsWithMetaParams struct {
	Column1     interface{} `json:"column_1"`
	Column2     interface{} `json:"column_2"`
	SortBy      interface{} `json:"sort_by"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

type ListPostsWithMetaRow struct {
	ID          int64         `json:"id"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	Content     string        `json:"content"`
	UserID      int64         `json:"user_id"`
	Username    string        `json:"username"`
	Url         string        `json:"url"`
	PostType    string        `json:"post_type"`
	PostStatus  string        `json:"post_status"`
	PostParent  sql.NullInt64 `json:"post_parent"`
	MenuOrder   int32         `json:"menu_order"`
	CreatedAt   time.Time     `json:"created_at"`
	ChangedAt   time.Time     `json:"changed_at"`
	Meta        interface{}   `json:"meta"`
}

func (q *Queries) ListPostsWithMeta(ctx context.Context, arg ListPostsWithMetaParams) ([]ListPostsWithMetaRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostsWithMeta,
		arg.Column1,
		arg.Column2,
		arg.SortBy,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsWithMetaRow{}
	for rows.Next() {
		var i ListPostsWithMetaRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.UserID,
			&i.Username,
			&i.Url,
			&i.PostType,
			&i.PostStatus,
			&i.PostParent,
			&i.MenuOrder,
			&i.CreatedAt,
			&i.ChangedAt,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET title = COALESCE($1, title),
    description = COALESCE($2, description),
    user_id = COALESCE($3, user_id),
    username = COALESCE($4, username),
    content = COALESCE($5, content),
    url = COALESCE($6, url),
    post_type = COALESCE($7, post_type),
    post_status = COALESCE($8, post_status),
    post_parent = COALESCE($9, post_parent),
    menu_order = COALESCE($10, menu_order),
    changed_at = now()
WHERE id = $11
RETURNING id, title, description, content, user_id, username, url, post_type, post_status, post_parent, menu_order, created_at, changed_at
`

type UpdatePostParams struct {
	Title       string        `json:"title"`
	Description string        `json:"description"`
	UserID      int64         `json:"user_id"`
	Username    string        `json:"username"`
	Content     string        `json:"content"`
	Url         string        `json:"url"`
	PostType    string        `json:"post_type"`
	PostStatus  string        `json:"post_status"`
	PostParent  sql.NullInt64 `json:"post_parent"`
	MenuOrder   int32         `json:"menu_order"`
	ID          int64         `json:"id"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, updatePost,
		arg.Title,
		arg.Description,
		arg.UserID,
		arg.Username,
		arg.Content,
		arg.Url,
		arg.PostType,
		arg.PostStatus,
		arg.PostParent,
		arg.MenuOrder,
		arg.ID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Content,
		&i.UserID,
		&i.Username,
		&i.Url,
		&i.PostType,
		&i.PostStatus,
		&i.PostParent,
		&i.MenuOrder,
		&i.CreatedAt,
		&i.ChangedAt,
	)
	return i, err
}
