// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: post_types.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createPostMeta = `-- name: CreatePostMeta :one
INSERT INTO post_meta (
    post_id,
    meta_key,
    meta_value
) VALUES (
    $1, $2, $3
) RETURNING id, post_id, meta_key, meta_value, created_at
`

type CreatePostMetaParams struct {
	PostID    int64          `json:"post_id"`
	MetaKey   string         `json:"meta_key"`
	MetaValue sql.NullString `json:"meta_value"`
}

func (q *Queries) CreatePostMeta(ctx context.Context, arg CreatePostMetaParams) (PostMetum, error) {
	row := q.db.QueryRowContext(ctx, createPostMeta, arg.PostID, arg.MetaKey, arg.MetaValue)
	var i PostMetum
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.MetaKey,
		&i.MetaValue,
		&i.CreatedAt,
	)
	return i, err
}

const createPostType = `-- name: CreatePostType :one
INSERT INTO post_types (
    name,
    label,
    description,
    public,
    hierarchical,
    has_archive,
    menu_position,
    supports
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, name, label, description, public, hierarchical, has_archive, menu_position, supports, created_at
`

type CreatePostTypeParams struct {
	Name         string          `json:"name"`
	Label        string          `json:"label"`
	Description  sql.NullString  `json:"description"`
	Public       bool            `json:"public"`
	Hierarchical bool            `json:"hierarchical"`
	HasArchive   bool            `json:"has_archive"`
	MenuPosition sql.NullInt32   `json:"menu_position"`
	Supports     json.RawMessage `json:"supports"`
}

func (q *Queries) CreatePostType(ctx context.Context, arg CreatePostTypeParams) (PostType, error) {
	row := q.db.QueryRowContext(ctx, createPostType,
		arg.Name,
		arg.Label,
		arg.Description,
		arg.Public,
		arg.Hierarchical,
		arg.HasArchive,
		arg.MenuPosition,
		arg.Supports,
	)
	var i PostType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Label,
		&i.Description,
		&i.Public,
		&i.Hierarchical,
		&i.HasArchive,
		&i.MenuPosition,
		&i.Supports,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllPostMeta = `-- name: DeleteAllPostMeta :exec
DELETE FROM post_meta
WHERE post_id = $1
`

func (q *Queries) DeleteAllPostMeta(ctx context.Context, postID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAllPostMeta, postID)
	return err
}

const deletePostMeta = `-- name: DeletePostMeta :exec
DELETE FROM post_meta
WHERE post_id = $1 AND meta_key = $2
`

type DeletePostMetaParams struct {
	PostID  int64  `json:"post_id"`
	MetaKey string `json:"meta_key"`
}

func (q *Queries) DeletePostMeta(ctx context.Context, arg DeletePostMetaParams) error {
	_, err := q.db.ExecContext(ctx, deletePostMeta, arg.PostID, arg.MetaKey)
	return err
}

const deletePostType = `-- name: DeletePostType :exec
DELETE FROM post_types
WHERE name = $1
`

func (q *Queries) DeletePostType(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deletePostType, name)
	return err
}

const getPostMeta = `-- name: GetPostMeta :many
SELECT id, post_id, meta_key, meta_value, created_at FROM post_meta
WHERE post_id = $1
ORDER BY meta_key ASC
`

func (q *Queries) GetPostMeta(ctx context.Context, postID int64) ([]PostMetum, error) {
	rows, err := q.db.QueryContext(ctx, getPostMeta, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostMetum{}
	for rows.Next() {
		var i PostMetum
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.MetaKey,
			&i.MetaValue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostMetaByKey = `-- name: GetPostMetaByKey :one
SELECT id, post_id, meta_key, meta_value, created_at FROM post_meta
WHERE post_id = $1 AND meta_key = $2 LIMIT 1
`

type GetPostMetaByKeyParams struct {
	PostID  int64  `json:"post_id"`
	MetaKey string `json:"meta_key"`
}

func (q *Queries) GetPostMetaByKey(ctx context.Context, arg GetPostMetaByKeyParams) (PostMetum, error) {
	row := q.db.QueryRowContext(ctx, getPostMetaByKey, arg.PostID, arg.MetaKey)
	var i PostMetum
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.MetaKey,
		&i.MetaValue,
		&i.CreatedAt,
	)
	return i, err
}

const getPostType = `-- name: GetPostType :one
SELECT id, name, label, description, public, hierarchical, has_archive, menu_position, supports, created_at FROM post_types 
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetPostType(ctx context.Context, name string) (PostType, error) {
	row := q.db.QueryRowContext(ctx, getPostType, name)
	var i PostType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Label,
		&i.Description,
		&i.Public,
		&i.Hierarchical,
		&i.HasArchive,
		&i.MenuPosition,
		&i.Supports,
		&i.CreatedAt,
	)
	return i, err
}

const getPostTypeByID = `-- name: GetPostTypeByID :one
SELECT id, name, label, description, public, hierarchical, has_archive, menu_position, supports, created_at FROM post_types 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPostTypeByID(ctx context.Context, id int64) (PostType, error) {
	row := q.db.QueryRowContext(ctx, getPostTypeByID, id)
	var i PostType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Label,
		&i.Description,
		&i.Public,
		&i.Hierarchical,
		&i.HasArchive,
		&i.MenuPosition,
		&i.Supports,
		&i.CreatedAt,
	)
	return i, err
}

const listPostTypes = `-- name: ListPostTypes :many
SELECT id, name, label, description, public, hierarchical, has_archive, menu_position, supports, created_at FROM post_types
ORDER BY menu_position ASC, name ASC
`

func (q *Queries) ListPostTypes(ctx context.Context) ([]PostType, error) {
	rows, err := q.db.QueryContext(ctx, listPostTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostType{}
	for rows.Next() {
		var i PostType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Label,
			&i.Description,
			&i.Public,
			&i.Hierarchical,
			&i.HasArchive,
			&i.MenuPosition,
			&i.Supports,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePostMeta = `-- name: UpdatePostMeta :one
UPDATE post_meta
SET meta_value = $3
WHERE post_id = $1 AND meta_key = $2
RETURNING id, post_id, meta_key, meta_value, created_at
`

type UpdatePostMetaParams struct {
	PostID    int64          `json:"post_id"`
	MetaKey   string         `json:"meta_key"`
	MetaValue sql.NullString `json:"meta_value"`
}

func (q *Queries) UpdatePostMeta(ctx context.Context, arg UpdatePostMetaParams) (PostMetum, error) {
	row := q.db.QueryRowContext(ctx, updatePostMeta, arg.PostID, arg.MetaKey, arg.MetaValue)
	var i PostMetum
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.MetaKey,
		&i.MetaValue,
		&i.CreatedAt,
	)
	return i, err
}

const updatePostType = `-- name: UpdatePostType :one
UPDATE post_types
SET label = COALESCE($1, label),
    description = COALESCE($2, description),
    public = COALESCE($3, public),
    hierarchical = COALESCE($4, hierarchical),
    has_archive = COALESCE($5, has_archive),
    menu_position = COALESCE($6, menu_position),
    supports = COALESCE($7, supports)
WHERE name = $8
RETURNING id, name, label, description, public, hierarchical, has_archive, menu_position, supports, created_at
`

type UpdatePostTypeParams struct {
	Label        string          `json:"label"`
	Description  sql.NullString  `json:"description"`
	Public       bool            `json:"public"`
	Hierarchical bool            `json:"hierarchical"`
	HasArchive   bool            `json:"has_archive"`
	MenuPosition sql.NullInt32   `json:"menu_position"`
	Supports     json.RawMessage `json:"supports"`
	Name         string          `json:"name"`
}

func (q *Queries) UpdatePostType(ctx context.Context, arg UpdatePostTypeParams) (PostType, error) {
	row := q.db.QueryRowContext(ctx, updatePostType,
		arg.Label,
		arg.Description,
		arg.Public,
		arg.Hierarchical,
		arg.HasArchive,
		arg.MenuPosition,
		arg.Supports,
		arg.Name,
	)
	var i PostType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Label,
		&i.Description,
		&i.Public,
		&i.Hierarchical,
		&i.HasArchive,
		&i.MenuPosition,
		&i.Supports,
		&i.CreatedAt,
	)
	return i, err
}

const upsertPostMeta = `-- name: UpsertPostMeta :one
INSERT INTO post_meta (post_id, meta_key, meta_value)
VALUES ($1, $2, $3)
ON CONFLICT (post_id, meta_key) 
DO UPDATE SET meta_value = EXCLUDED.meta_value
RETURNING id, post_id, meta_key, meta_value, created_at
`

type UpsertPostMetaParams struct {
	PostID    int64          `json:"post_id"`
	MetaKey   string         `json:"meta_key"`
	MetaValue sql.NullString `json:"meta_value"`
}

func (q *Queries) UpsertPostMeta(ctx context.Context, arg UpsertPostMetaParams) (PostMetum, error) {
	row := q.db.QueryRowContext(ctx, upsertPostMeta, arg.PostID, arg.MetaKey, arg.MetaValue)
	var i PostMetum
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.MetaKey,
		&i.MetaValue,
		&i.CreatedAt,
	)
	return i, err
}
