// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: session.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const blockAllSessionsForUser = `-- name: BlockAllSessionsForUser :exec
UPDATE sessions
SET is_blocked = true
WHERE user_id = $1 AND is_blocked = false
`

func (q *Queries) BlockAllSessionsForUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, blockAllSessionsForUser, userID)
	return err
}

const blockSession = `-- name: BlockSession :exec
UPDATE sessions
SET is_blocked = true
WHERE id = $1
`

func (q *Queries) BlockSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, blockSession, id)
	return err
}

const countTotalSessions = `-- name: CountTotalSessions :one
SELECT COUNT(*) AS total FROM sessions
`

func (q *Queries) CountTotalSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTotalSessions)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id,
    user_id,
    username,
    refresh_token,
    refresh_token_hash,
    refresh_kid,
    jti,
    user_agent,
    client_ip,
    is_blocked,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, user_id, username, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at, refresh_token_hash, refresh_kid, jti, rotated_at, replaced_by
`

type CreateSessionParams struct {
	ID               uuid.UUID      `json:"id"`
	UserID           int64          `json:"user_id"`
	Username         string         `json:"username"`
	RefreshToken     string         `json:"refresh_token"`
	RefreshTokenHash []byte         `json:"refresh_token_hash"`
	RefreshKid       sql.NullString `json:"refresh_kid"`
	Jti              uuid.NullUUID  `json:"jti"`
	UserAgent        string         `json:"user_agent"`
	ClientIp         string         `json:"client_ip"`
	IsBlocked        bool           `json:"is_blocked"`
	ExpiresAt        time.Time      `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.Username,
		arg.RefreshToken,
		arg.RefreshTokenHash,
		arg.RefreshKid,
		arg.Jti,
		arg.UserAgent,
		arg.ClientIp,
		arg.IsBlocked,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RefreshTokenHash,
		&i.RefreshKid,
		&i.Jti,
		&i.RotatedAt,
		&i.ReplacedBy,
	)
	return i, err
}

const getAnySessionByRefreshTokenHash = `-- name: GetAnySessionByRefreshTokenHash :one
SELECT id, user_id, username, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at, refresh_token_hash, refresh_kid, jti, rotated_at, replaced_by FROM sessions WHERE refresh_token_hash = $1 LIMIT 1
`

func (q *Queries) GetAnySessionByRefreshTokenHash(ctx context.Context, refreshTokenHash []byte) (Session, error) {
	row := q.db.QueryRowContext(ctx, getAnySessionByRefreshTokenHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RefreshTokenHash,
		&i.RefreshKid,
		&i.Jti,
		&i.RotatedAt,
		&i.ReplacedBy,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, username, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at, refresh_token_hash, refresh_kid, jti, rotated_at, replaced_by FROM sessions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RefreshTokenHash,
		&i.RefreshKid,
		&i.Jti,
		&i.RotatedAt,
		&i.ReplacedBy,
	)
	return i, err
}

const getSessionByRefreshTokenHash = `-- name: GetSessionByRefreshTokenHash :one
SELECT id, user_id, username, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at, refresh_token_hash, refresh_kid, jti, rotated_at, replaced_by FROM sessions
WHERE refresh_token_hash = $1 AND is_blocked = false LIMIT 1
`

func (q *Queries) GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash []byte) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByRefreshTokenHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RefreshTokenHash,
		&i.RefreshKid,
		&i.Jti,
		&i.RotatedAt,
		&i.ReplacedBy,
	)
	return i, err
}

const getSessionForUpdate = `-- name: GetSessionForUpdate :one
SELECT id, user_id, username, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at, refresh_token_hash, refresh_kid, jti, rotated_at, replaced_by FROM sessions WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetSessionForUpdate(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionForUpdate, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RefreshTokenHash,
		&i.RefreshKid,
		&i.Jti,
		&i.RotatedAt,
		&i.ReplacedBy,
	)
	return i, err
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT id, user_id, username, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at, refresh_token_hash, refresh_kid, jti, rotated_at, replaced_by FROM sessions
WHERE user_id = $1
`

func (q *Queries) ListSessionsByUser(ctx context.Context, userID int64) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.RefreshToken,
			&i.UserAgent,
			&i.ClientIp,
			&i.IsBlocked,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RefreshTokenHash,
			&i.RefreshKid,
			&i.Jti,
			&i.RotatedAt,
			&i.ReplacedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByUsername = `-- name: ListSessionsByUsername :many
SELECT id, user_id, username, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at, refresh_token_hash, refresh_kid, jti, rotated_at, replaced_by FROM sessions
WHERE username = $1
`

func (q *Queries) ListSessionsByUsername(ctx context.Context, username string) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByUsername, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.RefreshToken,
			&i.UserAgent,
			&i.ClientIp,
			&i.IsBlocked,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RefreshTokenHash,
			&i.RefreshKid,
			&i.Jti,
			&i.RotatedAt,
			&i.ReplacedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateToNewSession = `-- name: RotateToNewSession :execrows
UPDATE sessions
SET 
    rotated_at = NOW(),
    replaced_by = $2,
    is_blocked = true
WHERE id = $1 AND is_blocked = false
`

type RotateToNewSessionParams struct {
	ID         uuid.UUID     `json:"id"`
	ReplacedBy uuid.NullUUID `json:"replaced_by"`
}

func (q *Queries) RotateToNewSession(ctx context.Context, arg RotateToNewSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, rotateToNewSession, arg.ID, arg.ReplacedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions 
SET 
    username = COALESCE($2, username)
WHERE id = $1
RETURNING id, user_id, username, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at, refresh_token_hash, refresh_kid, jti, rotated_at, replaced_by
`

type UpdateSessionParams struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, updateSession, arg.ID, arg.Username)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RefreshTokenHash,
		&i.RefreshKid,
		&i.Jti,
		&i.RotatedAt,
		&i.ReplacedBy,
	)
	return i, err
}

const updateSessionsUsername = `-- name: UpdateSessionsUsername :many
UPDATE sessions
SET username = $2
WHERE username = $1
RETURNING id, user_id, username, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at, refresh_token_hash, refresh_kid, jti, rotated_at, replaced_by
`

type UpdateSessionsUsernameParams struct {
	Username   string `json:"username"`
	Username_2 string `json:"username_2"`
}

func (q *Queries) UpdateSessionsUsername(ctx context.Context, arg UpdateSessionsUsernameParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, updateSessionsUsername, arg.Username, arg.Username_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.RefreshToken,
			&i.UserAgent,
			&i.ClientIp,
			&i.IsBlocked,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RefreshTokenHash,
			&i.RefreshKid,
			&i.Jti,
			&i.RotatedAt,
			&i.ReplacedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
