// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: settings.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const deleteExtensionSetting = `-- name: DeleteExtensionSetting :exec
DELETE FROM extension_settings WHERE key = $1
`

func (q *Queries) DeleteExtensionSetting(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteExtensionSetting, key)
	return err
}

const deleteExtensionSettingsByExtension = `-- name: DeleteExtensionSettingsByExtension :exec
DELETE FROM extension_settings 
WHERE extension_type = $1 AND extension_id = $2
`

type DeleteExtensionSettingsByExtensionParams struct {
	ExtensionType string `json:"extension_type"`
	ExtensionID   string `json:"extension_id"`
}

func (q *Queries) DeleteExtensionSettingsByExtension(ctx context.Context, arg DeleteExtensionSettingsByExtensionParams) error {
	_, err := q.db.ExecContext(ctx, deleteExtensionSettingsByExtension, arg.ExtensionType, arg.ExtensionID)
	return err
}

const getExtensionSetting = `-- name: GetExtensionSetting :one
SELECT key, value, extension_type, extension_id, created_at, changed_at FROM extension_settings WHERE key = $1
`

func (q *Queries) GetExtensionSetting(ctx context.Context, key string) (ExtensionSetting, error) {
	row := q.db.QueryRowContext(ctx, getExtensionSetting, key)
	var i ExtensionSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.ExtensionType,
		&i.ExtensionID,
		&i.CreatedAt,
		&i.ChangedAt,
	)
	return i, err
}

const getSettings = `-- name: GetSettings :one
SELECT id, post_url_structure, site_title, posts_per_page, created_at, changed_at FROM settings WHERE id = 1
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.PostUrlStructure,
		&i.SiteTitle,
		&i.PostsPerPage,
		&i.CreatedAt,
		&i.ChangedAt,
	)
	return i, err
}

const listExtensionSettings = `-- name: ListExtensionSettings :many
SELECT key, value, extension_type, extension_id, created_at, changed_at FROM extension_settings
ORDER BY extension_type, extension_id, key
`

func (q *Queries) ListExtensionSettings(ctx context.Context) ([]ExtensionSetting, error) {
	rows, err := q.db.QueryContext(ctx, listExtensionSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExtensionSetting{}
	for rows.Next() {
		var i ExtensionSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.ExtensionType,
			&i.ExtensionID,
			&i.CreatedAt,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExtensionSettingsByExtension = `-- name: ListExtensionSettingsByExtension :many
SELECT key, value, extension_type, extension_id, created_at, changed_at FROM extension_settings
WHERE extension_type = $1 AND extension_id = $2
ORDER BY key
`

type ListExtensionSettingsByExtensionParams struct {
	ExtensionType string `json:"extension_type"`
	ExtensionID   string `json:"extension_id"`
}

func (q *Queries) ListExtensionSettingsByExtension(ctx context.Context, arg ListExtensionSettingsByExtensionParams) ([]ExtensionSetting, error) {
	rows, err := q.db.QueryContext(ctx, listExtensionSettingsByExtension, arg.ExtensionType, arg.ExtensionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExtensionSetting{}
	for rows.Next() {
		var i ExtensionSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.ExtensionType,
			&i.ExtensionID,
			&i.CreatedAt,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSettings = `-- name: UpdateSettings :one
UPDATE settings
SET 
  post_url_structure = COALESCE($1, post_url_structure),
  site_title = COALESCE($2, site_title),
  posts_per_page = COALESCE($3, posts_per_page),
  changed_at = now()
WHERE id = 1
RETURNING id, post_url_structure, site_title, posts_per_page, created_at, changed_at
`

type UpdateSettingsParams struct {
	PostUrlStructure sql.NullString `json:"post_url_structure"`
	SiteTitle        sql.NullString `json:"site_title"`
	PostsPerPage     sql.NullInt32  `json:"posts_per_page"`
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, updateSettings, arg.PostUrlStructure, arg.SiteTitle, arg.PostsPerPage)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.PostUrlStructure,
		&i.SiteTitle,
		&i.PostsPerPage,
		&i.CreatedAt,
		&i.ChangedAt,
	)
	return i, err
}

const upsertExtensionSetting = `-- name: UpsertExtensionSetting :one
INSERT INTO extension_settings (key, value, extension_type, extension_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value,
    changed_at = now()
RETURNING key, value, extension_type, extension_id, created_at, changed_at
`

type UpsertExtensionSettingParams struct {
	Key           string          `json:"key"`
	Value         json.RawMessage `json:"value"`
	ExtensionType string          `json:"extension_type"`
	ExtensionID   string          `json:"extension_id"`
}

func (q *Queries) UpsertExtensionSetting(ctx context.Context, arg UpsertExtensionSettingParams) (ExtensionSetting, error) {
	row := q.db.QueryRowContext(ctx, upsertExtensionSetting,
		arg.Key,
		arg.Value,
		arg.ExtensionType,
		arg.ExtensionID,
	)
	var i ExtensionSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.ExtensionType,
		&i.ExtensionID,
		&i.CreatedAt,
		&i.ChangedAt,
	)
	return i, err
}
