// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: taxonomy_system.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const addPostToTaxonomyTerm = `-- name: AddPostToTaxonomyTerm :one
INSERT INTO post_taxonomy_relationships (post_id, taxonomy_term_id)
VALUES ($1, $2) RETURNING post_id, taxonomy_term_id, created_at
`

type AddPostToTaxonomyTermParams struct {
	PostID         int64 `json:"post_id"`
	TaxonomyTermID int64 `json:"taxonomy_term_id"`
}

// Post-Taxonomy Relationships
func (q *Queries) AddPostToTaxonomyTerm(ctx context.Context, arg AddPostToTaxonomyTermParams) (PostTaxonomyRelationship, error) {
	row := q.db.QueryRowContext(ctx, addPostToTaxonomyTerm, arg.PostID, arg.TaxonomyTermID)
	var i PostTaxonomyRelationship
	err := row.Scan(&i.PostID, &i.TaxonomyTermID, &i.CreatedAt)
	return i, err
}

const countPostsByTaxonomyTerm = `-- name: CountPostsByTaxonomyTerm :one
SELECT COUNT(*) as total FROM post_taxonomy_relationships
WHERE taxonomy_term_id = $1
`

func (q *Queries) CountPostsByTaxonomyTerm(ctx context.Context, taxonomyTermID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPostsByTaxonomyTerm, taxonomyTermID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countTaxonomyTerms = `-- name: CountTaxonomyTerms :one
SELECT COUNT(*) as total FROM taxonomy_terms tt
JOIN taxonomy_types ttype ON tt.taxonomy_type_id = ttype.id
WHERE ttype.name = $1
`

// Counting functions
func (q *Queries) CountTaxonomyTerms(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTaxonomyTerms, name)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createTaxonomyTerm = `-- name: CreateTaxonomyTerm :one
INSERT INTO taxonomy_terms (name, slug, description, parent_id, taxonomy_type_id, sort_order, meta)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, name, slug, description, parent_id, taxonomy_type_id, sort_order, meta, created_at
`

type CreateTaxonomyTermParams struct {
	Name           string                `json:"name"`
	Slug           string                `json:"slug"`
	Description    sql.NullString        `json:"description"`
	ParentID       sql.NullInt64         `json:"parent_id"`
	TaxonomyTypeID int64                 `json:"taxonomy_type_id"`
	SortOrder      sql.NullInt32         `json:"sort_order"`
	Meta           pqtype.NullRawMessage `json:"meta"`
}

// Taxonomy Terms Management
func (q *Queries) CreateTaxonomyTerm(ctx context.Context, arg CreateTaxonomyTermParams) (TaxonomyTerm, error) {
	row := q.db.QueryRowContext(ctx, createTaxonomyTerm,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ParentID,
		arg.TaxonomyTypeID,
		arg.SortOrder,
		arg.Meta,
	)
	var i TaxonomyTerm
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ParentID,
		&i.TaxonomyTypeID,
		&i.SortOrder,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}

const createTaxonomyType = `-- name: CreateTaxonomyType :one
INSERT INTO taxonomy_types (name, label, description, hierarchical, public, show_ui, show_in_menu)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, name, label, description, hierarchical, public, show_ui, show_in_menu, created_at
`

type CreateTaxonomyTypeParams struct {
	Name         string         `json:"name"`
	Label        string         `json:"label"`
	Description  sql.NullString `json:"description"`
	Hierarchical bool           `json:"hierarchical"`
	Public       bool           `json:"public"`
	ShowUi       bool           `json:"show_ui"`
	ShowInMenu   bool           `json:"show_in_menu"`
}

// Taxonomy Types Management
func (q *Queries) CreateTaxonomyType(ctx context.Context, arg CreateTaxonomyTypeParams) (TaxonomyType, error) {
	row := q.db.QueryRowContext(ctx, createTaxonomyType,
		arg.Name,
		arg.Label,
		arg.Description,
		arg.Hierarchical,
		arg.Public,
		arg.ShowUi,
		arg.ShowInMenu,
	)
	var i TaxonomyType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Label,
		&i.Description,
		&i.Hierarchical,
		&i.Public,
		&i.ShowUi,
		&i.ShowInMenu,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTaxonomyTerm = `-- name: DeleteTaxonomyTerm :exec
DELETE FROM taxonomy_terms WHERE id = $1
`

func (q *Queries) DeleteTaxonomyTerm(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTaxonomyTerm, id)
	return err
}

const deleteTaxonomyType = `-- name: DeleteTaxonomyType :exec
DELETE FROM taxonomy_types WHERE name = $1
`

func (q *Queries) DeleteTaxonomyType(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteTaxonomyType, name)
	return err
}

const getPopularTaxonomyTerms = `-- name: GetPopularTaxonomyTerms :many
SELECT 
    tt.id, tt.name, tt.slug, tt.description, tt.parent_id, tt.taxonomy_type_id, tt.sort_order, tt.meta, tt.created_at,
    ttype.name as taxonomy_type_name,
    COUNT(ptr.post_id) as post_count
FROM taxonomy_terms tt
JOIN taxonomy_types ttype ON tt.taxonomy_type_id = ttype.id
JOIN post_taxonomy_relationships ptr ON tt.id = ptr.taxonomy_term_id
WHERE ttype.name = $1
GROUP BY tt.id, tt.name, tt.slug, tt.description, tt.parent_id, tt.taxonomy_type_id, tt.sort_order, tt.meta, tt.created_at, ttype.name
HAVING COUNT(ptr.post_id) > 0
ORDER BY COUNT(ptr.post_id) DESC
LIMIT $2
`

type GetPopularTaxonomyTermsParams struct {
	Name  string `json:"name"`
	Limit int32  `json:"limit"`
}

type GetPopularTaxonomyTermsRow struct {
	ID               int64                 `json:"id"`
	Name             string                `json:"name"`
	Slug             string                `json:"slug"`
	Description      sql.NullString        `json:"description"`
	ParentID         sql.NullInt64         `json:"parent_id"`
	TaxonomyTypeID   int64                 `json:"taxonomy_type_id"`
	SortOrder        sql.NullInt32         `json:"sort_order"`
	Meta             pqtype.NullRawMessage `json:"meta"`
	CreatedAt        time.Time             `json:"created_at"`
	TaxonomyTypeName string                `json:"taxonomy_type_name"`
	PostCount        int64                 `json:"post_count"`
}

func (q *Queries) GetPopularTaxonomyTerms(ctx context.Context, arg GetPopularTaxonomyTermsParams) ([]GetPopularTaxonomyTermsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPopularTaxonomyTerms, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPopularTaxonomyTermsRow{}
	for rows.Next() {
		var i GetPopularTaxonomyTermsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ParentID,
			&i.TaxonomyTypeID,
			&i.SortOrder,
			&i.Meta,
			&i.CreatedAt,
			&i.TaxonomyTypeName,
			&i.PostCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostTaxonomyTerms = `-- name: GetPostTaxonomyTerms :many
SELECT tt.id, tt.name, tt.slug, tt.description, tt.parent_id, tt.taxonomy_type_id, tt.sort_order, tt.meta, tt.created_at, ttype.name as taxonomy_type_name, ttype.hierarchical
FROM taxonomy_terms tt
JOIN taxonomy_types ttype ON tt.taxonomy_type_id = ttype.id
JOIN post_taxonomy_relationships ptr ON tt.id = ptr.taxonomy_term_id
WHERE ptr.post_id = $1
ORDER BY ttype.name, tt.name
`

type GetPostTaxonomyTermsRow struct {
	ID               int64                 `json:"id"`
	Name             string                `json:"name"`
	Slug             string                `json:"slug"`
	Description      sql.NullString        `json:"description"`
	ParentID         sql.NullInt64         `json:"parent_id"`
	TaxonomyTypeID   int64                 `json:"taxonomy_type_id"`
	SortOrder        sql.NullInt32         `json:"sort_order"`
	Meta             pqtype.NullRawMessage `json:"meta"`
	CreatedAt        time.Time             `json:"created_at"`
	TaxonomyTypeName string                `json:"taxonomy_type_name"`
	Hierarchical     bool                  `json:"hierarchical"`
}

func (q *Queries) GetPostTaxonomyTerms(ctx context.Context, postID int64) ([]GetPostTaxonomyTermsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostTaxonomyTerms, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPostTaxonomyTermsRow{}
	for rows.Next() {
		var i GetPostTaxonomyTermsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ParentID,
			&i.TaxonomyTypeID,
			&i.SortOrder,
			&i.Meta,
			&i.CreatedAt,
			&i.TaxonomyTypeName,
			&i.Hierarchical,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsByMultipleTaxonomyTerms = `-- name: GetPostsByMultipleTaxonomyTerms :many
SELECT DISTINCT p.id, p.title, p.description, p.content, p.user_id, p.username, p.url, p.post_type, p.post_status, p.post_parent, p.menu_order, p.created_at, p.changed_at
FROM posts p
JOIN post_taxonomy_relationships ptr ON p.id = ptr.post_id
WHERE ptr.taxonomy_term_id = ANY($1::bigint[])
    AND ($2 = '' OR p.post_status = $2)
ORDER BY p.created_at DESC
LIMIT $4 OFFSET $3
`

type GetPostsByMultipleTaxonomyTermsParams struct {
	Column1     []int64     `json:"column_1"`
	Column2     interface{} `json:"column_2"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

func (q *Queries) GetPostsByMultipleTaxonomyTerms(ctx context.Context, arg GetPostsByMultipleTaxonomyTermsParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPostsByMultipleTaxonomyTerms,
		pq.Array(arg.Column1),
		arg.Column2,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.UserID,
			&i.Username,
			&i.Url,
			&i.PostType,
			&i.PostStatus,
			&i.PostParent,
			&i.MenuOrder,
			&i.CreatedAt,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsByTaxonomyTerm = `-- name: GetPostsByTaxonomyTerm :many
SELECT p.id, p.title, p.description, p.content, p.user_id, p.username, p.url, p.post_type, p.post_status, p.post_parent, p.menu_order, p.created_at, p.changed_at
FROM posts p
JOIN post_taxonomy_relationships ptr ON p.id = ptr.post_id
WHERE ptr.taxonomy_term_id = $1
    AND ($2 = '' OR p.post_status = $2)
ORDER BY
    CASE WHEN $3 = 'date_asc' THEN p.created_at END ASC,
    CASE WHEN $3 = 'date_desc' THEN p.created_at END DESC,
    CASE WHEN $3 = 'title_asc' THEN p.title END ASC,
    CASE WHEN $3 = 'title_desc' THEN p.title END DESC,
    p.created_at DESC
LIMIT $5 OFFSET $4
`

type GetPostsByTaxonomyTermParams struct {
	TaxonomyTermID int64       `json:"taxonomy_term_id"`
	Column2        interface{} `json:"column_2"`
	SortBy         interface{} `json:"sort_by"`
	OffsetCount    int32       `json:"offset_count"`
	LimitCount     int32       `json:"limit_count"`
}

func (q *Queries) GetPostsByTaxonomyTerm(ctx context.Context, arg GetPostsByTaxonomyTermParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPostsByTaxonomyTerm,
		arg.TaxonomyTermID,
		arg.Column2,
		arg.SortBy,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.UserID,
			&i.Username,
			&i.Url,
			&i.PostType,
			&i.PostStatus,
			&i.PostParent,
			&i.MenuOrder,
			&i.CreatedAt,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaxonomyTerm = `-- name: GetTaxonomyTerm :one
SELECT id, name, slug, description, parent_id, taxonomy_type_id, sort_order, meta, created_at FROM taxonomy_terms WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTaxonomyTerm(ctx context.Context, id int64) (TaxonomyTerm, error) {
	row := q.db.QueryRowContext(ctx, getTaxonomyTerm, id)
	var i TaxonomyTerm
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ParentID,
		&i.TaxonomyTypeID,
		&i.SortOrder,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}

const getTaxonomyTermBySlug = `-- name: GetTaxonomyTermBySlug :one
SELECT tt.id, tt.name, tt.slug, tt.description, tt.parent_id, tt.taxonomy_type_id, tt.sort_order, tt.meta, tt.created_at, ttype.name as taxonomy_type_name, ttype.hierarchical
FROM taxonomy_terms tt
JOIN taxonomy_types ttype ON tt.taxonomy_type_id = ttype.id
WHERE tt.slug = $1 LIMIT 1
`

type GetTaxonomyTermBySlugRow struct {
	ID               int64                 `json:"id"`
	Name             string                `json:"name"`
	Slug             string                `json:"slug"`
	Description      sql.NullString        `json:"description"`
	ParentID         sql.NullInt64         `json:"parent_id"`
	TaxonomyTypeID   int64                 `json:"taxonomy_type_id"`
	SortOrder        sql.NullInt32         `json:"sort_order"`
	Meta             pqtype.NullRawMessage `json:"meta"`
	CreatedAt        time.Time             `json:"created_at"`
	TaxonomyTypeName string                `json:"taxonomy_type_name"`
	Hierarchical     bool                  `json:"hierarchical"`
}

func (q *Queries) GetTaxonomyTermBySlug(ctx context.Context, slug string) (GetTaxonomyTermBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getTaxonomyTermBySlug, slug)
	var i GetTaxonomyTermBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ParentID,
		&i.TaxonomyTypeID,
		&i.SortOrder,
		&i.Meta,
		&i.CreatedAt,
		&i.TaxonomyTypeName,
		&i.Hierarchical,
	)
	return i, err
}

const getTaxonomyTermTree = `-- name: GetTaxonomyTermTree :many
WITH RECURSIVE term_tree AS (
    -- Root terms
    SELECT tt.id, tt.name, tt.slug, tt.description, tt.parent_id, tt.taxonomy_type_id, tt.sort_order, tt.meta, tt.created_at, ttype.name as taxonomy_type_name, 0 as level
    FROM taxonomy_terms tt
    JOIN taxonomy_types ttype ON tt.taxonomy_type_id = ttype.id
    WHERE tt.parent_id IS NULL AND ttype.name = $1
    
    UNION ALL
    
    -- Child terms
    SELECT tt.id, tt.name, tt.slug, tt.description, tt.parent_id, tt.taxonomy_type_id, tt.sort_order, tt.meta, tt.created_at, tree.taxonomy_type_name, tree.level + 1
    FROM taxonomy_terms tt
    JOIN term_tree tree ON tt.parent_id = tree.id
)
SELECT id, name, slug, description, parent_id, taxonomy_type_id, sort_order, meta, created_at, taxonomy_type_name, level FROM term_tree ORDER BY level, sort_order, name
`

type GetTaxonomyTermTreeRow struct {
	ID               int64                 `json:"id"`
	Name             string                `json:"name"`
	Slug             string                `json:"slug"`
	Description      sql.NullString        `json:"description"`
	ParentID         sql.NullInt64         `json:"parent_id"`
	TaxonomyTypeID   int64                 `json:"taxonomy_type_id"`
	SortOrder        sql.NullInt32         `json:"sort_order"`
	Meta             pqtype.NullRawMessage `json:"meta"`
	CreatedAt        time.Time             `json:"created_at"`
	TaxonomyTypeName string                `json:"taxonomy_type_name"`
	Level            int32                 `json:"level"`
}

// Hierarchical term tree (for categories)
func (q *Queries) GetTaxonomyTermTree(ctx context.Context, name string) ([]GetTaxonomyTermTreeRow, error) {
	rows, err := q.db.QueryContext(ctx, getTaxonomyTermTree, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTaxonomyTermTreeRow{}
	for rows.Next() {
		var i GetTaxonomyTermTreeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ParentID,
			&i.TaxonomyTypeID,
			&i.SortOrder,
			&i.Meta,
			&i.CreatedAt,
			&i.TaxonomyTypeName,
			&i.Level,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaxonomyTermsWithPostCount = `-- name: GetTaxonomyTermsWithPostCount :many
SELECT 
    tt.id, tt.name, tt.slug, tt.description, tt.parent_id, tt.taxonomy_type_id, tt.sort_order, tt.meta, tt.created_at,
    ttype.name as taxonomy_type_name,
    ttype.hierarchical,
    COUNT(ptr.post_id) as post_count
FROM taxonomy_terms tt
JOIN taxonomy_types ttype ON tt.taxonomy_type_id = ttype.id
LEFT JOIN post_taxonomy_relationships ptr ON tt.id = ptr.taxonomy_term_id
WHERE ttype.name = $1
GROUP BY tt.id, tt.name, tt.slug, tt.description, tt.parent_id, tt.taxonomy_type_id, tt.sort_order, tt.meta, tt.created_at, ttype.name, ttype.hierarchical
ORDER BY tt.sort_order ASC, tt.name ASC
LIMIT $3 OFFSET $2
`

type GetTaxonomyTermsWithPostCountParams struct {
	Name        string `json:"name"`
	OffsetCount int32  `json:"offset_count"`
	LimitCount  int32  `json:"limit_count"`
}

type GetTaxonomyTermsWithPostCountRow struct {
	ID               int64                 `json:"id"`
	Name             string                `json:"name"`
	Slug             string                `json:"slug"`
	Description      sql.NullString        `json:"description"`
	ParentID         sql.NullInt64         `json:"parent_id"`
	TaxonomyTypeID   int64                 `json:"taxonomy_type_id"`
	SortOrder        sql.NullInt32         `json:"sort_order"`
	Meta             pqtype.NullRawMessage `json:"meta"`
	CreatedAt        time.Time             `json:"created_at"`
	TaxonomyTypeName string                `json:"taxonomy_type_name"`
	Hierarchical     bool                  `json:"hierarchical"`
	PostCount        int64                 `json:"post_count"`
}

func (q *Queries) GetTaxonomyTermsWithPostCount(ctx context.Context, arg GetTaxonomyTermsWithPostCountParams) ([]GetTaxonomyTermsWithPostCountRow, error) {
	rows, err := q.db.QueryContext(ctx, getTaxonomyTermsWithPostCount, arg.Name, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTaxonomyTermsWithPostCountRow{}
	for rows.Next() {
		var i GetTaxonomyTermsWithPostCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ParentID,
			&i.TaxonomyTypeID,
			&i.SortOrder,
			&i.Meta,
			&i.CreatedAt,
			&i.TaxonomyTypeName,
			&i.Hierarchical,
			&i.PostCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaxonomyType = `-- name: GetTaxonomyType :one
SELECT id, name, label, description, hierarchical, public, show_ui, show_in_menu, created_at FROM taxonomy_types WHERE name = $1 LIMIT 1
`

func (q *Queries) GetTaxonomyType(ctx context.Context, name string) (TaxonomyType, error) {
	row := q.db.QueryRowContext(ctx, getTaxonomyType, name)
	var i TaxonomyType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Label,
		&i.Description,
		&i.Hierarchical,
		&i.Public,
		&i.ShowUi,
		&i.ShowInMenu,
		&i.CreatedAt,
	)
	return i, err
}

const getTaxonomyTypeByID = `-- name: GetTaxonomyTypeByID :one
SELECT id, name, label, description, hierarchical, public, show_ui, show_in_menu, created_at FROM taxonomy_types WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTaxonomyTypeByID(ctx context.Context, id int64) (TaxonomyType, error) {
	row := q.db.QueryRowContext(ctx, getTaxonomyTypeByID, id)
	var i TaxonomyType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Label,
		&i.Description,
		&i.Hierarchical,
		&i.Public,
		&i.ShowUi,
		&i.ShowInMenu,
		&i.CreatedAt,
	)
	return i, err
}

const getTermChildren = `-- name: GetTermChildren :many
SELECT id, name, slug, description, parent_id, taxonomy_type_id, sort_order, meta, created_at FROM taxonomy_terms 
WHERE parent_id = $1 
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) GetTermChildren(ctx context.Context, parentID sql.NullInt64) ([]TaxonomyTerm, error) {
	rows, err := q.db.QueryContext(ctx, getTermChildren, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaxonomyTerm{}
	for rows.Next() {
		var i TaxonomyTerm
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ParentID,
			&i.TaxonomyTypeID,
			&i.SortOrder,
			&i.Meta,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTermParents = `-- name: GetTermParents :many
SELECT t1.id, t1.name, t1.slug, t1.description, t1.parent_id, t1.taxonomy_type_id, t1.sort_order, t1.meta, t1.created_at
FROM taxonomy_terms t1
JOIN taxonomy_terms t2 ON t1.id = t2.parent_id
WHERE t2.id = $1
ORDER BY t1.id
`

func (q *Queries) GetTermParents(ctx context.Context, id int64) ([]TaxonomyTerm, error) {
	rows, err := q.db.QueryContext(ctx, getTermParents, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaxonomyTerm{}
	for rows.Next() {
		var i TaxonomyTerm
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ParentID,
			&i.TaxonomyTypeID,
			&i.SortOrder,
			&i.Meta,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaxonomyTermsByType = `-- name: ListTaxonomyTermsByType :many
SELECT tt.id, tt.name, tt.slug, tt.description, tt.parent_id, tt.taxonomy_type_id, tt.sort_order, tt.meta, tt.created_at, ttype.name as taxonomy_type_name, ttype.hierarchical
FROM taxonomy_terms tt
JOIN taxonomy_types ttype ON tt.taxonomy_type_id = ttype.id
WHERE ttype.name = $1
ORDER BY
    CASE WHEN $2 = 'name_asc' THEN tt.name END ASC,
    CASE WHEN $2 = 'name_desc' THEN tt.name END DESC,
    CASE WHEN $2 = 'order_asc' THEN tt.sort_order END ASC,
    CASE WHEN $2 = 'order_desc' THEN tt.sort_order END DESC,
    CASE WHEN $2 = 'id_asc' THEN tt.id END ASC,
    CASE WHEN $2 = 'id_desc' THEN tt.id END DESC,
    tt.sort_order ASC, tt.name ASC
LIMIT $4 OFFSET $3
`

type ListTaxonomyTermsByTypeParams struct {
	Name        string      `json:"name"`
	SortBy      interface{} `json:"sort_by"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

type ListTaxonomyTermsByTypeRow struct {
	ID               int64                 `json:"id"`
	Name             string                `json:"name"`
	Slug             string                `json:"slug"`
	Description      sql.NullString        `json:"description"`
	ParentID         sql.NullInt64         `json:"parent_id"`
	TaxonomyTypeID   int64                 `json:"taxonomy_type_id"`
	SortOrder        sql.NullInt32         `json:"sort_order"`
	Meta             pqtype.NullRawMessage `json:"meta"`
	CreatedAt        time.Time             `json:"created_at"`
	TaxonomyTypeName string                `json:"taxonomy_type_name"`
	Hierarchical     bool                  `json:"hierarchical"`
}

func (q *Queries) ListTaxonomyTermsByType(ctx context.Context, arg ListTaxonomyTermsByTypeParams) ([]ListTaxonomyTermsByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, listTaxonomyTermsByType,
		arg.Name,
		arg.SortBy,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaxonomyTermsByTypeRow{}
	for rows.Next() {
		var i ListTaxonomyTermsByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ParentID,
			&i.TaxonomyTypeID,
			&i.SortOrder,
			&i.Meta,
			&i.CreatedAt,
			&i.TaxonomyTypeName,
			&i.Hierarchical,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaxonomyTypes = `-- name: ListTaxonomyTypes :many
SELECT id, name, label, description, hierarchical, public, show_ui, show_in_menu, created_at FROM taxonomy_types ORDER BY name
`

func (q *Queries) ListTaxonomyTypes(ctx context.Context) ([]TaxonomyType, error) {
	rows, err := q.db.QueryContext(ctx, listTaxonomyTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaxonomyType{}
	for rows.Next() {
		var i TaxonomyType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Label,
			&i.Description,
			&i.Hierarchical,
			&i.Public,
			&i.ShowUi,
			&i.ShowInMenu,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllPostTaxonomies = `-- name: RemoveAllPostTaxonomies :exec
DELETE FROM post_taxonomy_relationships WHERE post_id = $1
`

func (q *Queries) RemoveAllPostTaxonomies(ctx context.Context, postID int64) error {
	_, err := q.db.ExecContext(ctx, removeAllPostTaxonomies, postID)
	return err
}

const removeAllPostTaxonomiesByTerm = `-- name: RemoveAllPostTaxonomiesByTerm :exec
DELETE FROM post_taxonomy_relationships WHERE taxonomy_term_id = $1
`

func (q *Queries) RemoveAllPostTaxonomiesByTerm(ctx context.Context, taxonomyTermID int64) error {
	_, err := q.db.ExecContext(ctx, removeAllPostTaxonomiesByTerm, taxonomyTermID)
	return err
}

const removePostFromTaxonomyTerm = `-- name: RemovePostFromTaxonomyTerm :exec
DELETE FROM post_taxonomy_relationships
WHERE post_id = $1 AND taxonomy_term_id = $2
`

type RemovePostFromTaxonomyTermParams struct {
	PostID         int64 `json:"post_id"`
	TaxonomyTermID int64 `json:"taxonomy_term_id"`
}

func (q *Queries) RemovePostFromTaxonomyTerm(ctx context.Context, arg RemovePostFromTaxonomyTermParams) error {
	_, err := q.db.ExecContext(ctx, removePostFromTaxonomyTerm, arg.PostID, arg.TaxonomyTermID)
	return err
}

const searchTaxonomyTerms = `-- name: SearchTaxonomyTerms :many
SELECT tt.id, tt.name, tt.slug, tt.description, tt.parent_id, tt.taxonomy_type_id, tt.sort_order, tt.meta, tt.created_at, ttype.name as taxonomy_type_name
FROM taxonomy_terms tt
JOIN taxonomy_types ttype ON tt.taxonomy_type_id = ttype.id
WHERE ttype.name = $1 
    AND (tt.name ILIKE '%' || $2 || '%' OR tt.description ILIKE '%' || $2 || '%')
ORDER BY tt.name
LIMIT $4 OFFSET $3
`

type SearchTaxonomyTermsParams struct {
	Name        string         `json:"name"`
	Column2     sql.NullString `json:"column_2"`
	OffsetCount int32          `json:"offset_count"`
	LimitCount  int32          `json:"limit_count"`
}

type SearchTaxonomyTermsRow struct {
	ID               int64                 `json:"id"`
	Name             string                `json:"name"`
	Slug             string                `json:"slug"`
	Description      sql.NullString        `json:"description"`
	ParentID         sql.NullInt64         `json:"parent_id"`
	TaxonomyTypeID   int64                 `json:"taxonomy_type_id"`
	SortOrder        sql.NullInt32         `json:"sort_order"`
	Meta             pqtype.NullRawMessage `json:"meta"`
	CreatedAt        time.Time             `json:"created_at"`
	TaxonomyTypeName string                `json:"taxonomy_type_name"`
}

// Search and filtering
func (q *Queries) SearchTaxonomyTerms(ctx context.Context, arg SearchTaxonomyTermsParams) ([]SearchTaxonomyTermsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchTaxonomyTerms,
		arg.Name,
		arg.Column2,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTaxonomyTermsRow{}
	for rows.Next() {
		var i SearchTaxonomyTermsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ParentID,
			&i.TaxonomyTypeID,
			&i.SortOrder,
			&i.Meta,
			&i.CreatedAt,
			&i.TaxonomyTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaxonomyTerm = `-- name: UpdateTaxonomyTerm :one
UPDATE taxonomy_terms
SET name = COALESCE($2, name),
    slug = COALESCE($3, slug),
    description = COALESCE($4, description),
    parent_id = COALESCE($5, parent_id),
    sort_order = COALESCE($6, sort_order),
    meta = COALESCE($7, meta)
WHERE id = $1
RETURNING id, name, slug, description, parent_id, taxonomy_type_id, sort_order, meta, created_at
`

type UpdateTaxonomyTermParams struct {
	ID          int64                 `json:"id"`
	Name        string                `json:"name"`
	Slug        string                `json:"slug"`
	Description sql.NullString        `json:"description"`
	ParentID    sql.NullInt64         `json:"parent_id"`
	SortOrder   sql.NullInt32         `json:"sort_order"`
	Meta        pqtype.NullRawMessage `json:"meta"`
}

func (q *Queries) UpdateTaxonomyTerm(ctx context.Context, arg UpdateTaxonomyTermParams) (TaxonomyTerm, error) {
	row := q.db.QueryRowContext(ctx, updateTaxonomyTerm,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ParentID,
		arg.SortOrder,
		arg.Meta,
	)
	var i TaxonomyTerm
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ParentID,
		&i.TaxonomyTypeID,
		&i.SortOrder,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}

const updateTaxonomyType = `-- name: UpdateTaxonomyType :one
UPDATE taxonomy_types
SET label = COALESCE($2, label),
    description = COALESCE($3, description),
    hierarchical = COALESCE($4, hierarchical),
    public = COALESCE($5, public),
    show_ui = COALESCE($6, show_ui),
    show_in_menu = COALESCE($7, show_in_menu)
WHERE name = $1
RETURNING id, name, label, description, hierarchical, public, show_ui, show_in_menu, created_at
`

type UpdateTaxonomyTypeParams struct {
	Name         string         `json:"name"`
	Label        string         `json:"label"`
	Description  sql.NullString `json:"description"`
	Hierarchical bool           `json:"hierarchical"`
	Public       bool           `json:"public"`
	ShowUi       bool           `json:"show_ui"`
	ShowInMenu   bool           `json:"show_in_menu"`
}

func (q *Queries) UpdateTaxonomyType(ctx context.Context, arg UpdateTaxonomyTypeParams) (TaxonomyType, error) {
	row := q.db.QueryRowContext(ctx, updateTaxonomyType,
		arg.Name,
		arg.Label,
		arg.Description,
		arg.Hierarchical,
		arg.Public,
		arg.ShowUi,
		arg.ShowInMenu,
	)
	var i TaxonomyType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Label,
		&i.Description,
		&i.Hierarchical,
		&i.Public,
		&i.ShowUi,
		&i.ShowInMenu,
		&i.CreatedAt,
	)
	return i, err
}
