// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: themes.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const activateTheme = `-- name: ActivateTheme :one
WITH deactivated AS (
  UPDATE themes SET active = false, changed_at = now()
  WHERE active = true
  RETURNING id
)
UPDATE themes
SET active = true, changed_at = now()
WHERE themes.id = $1
RETURNING id, name, slug, description, version, author, config, active, created_at, changed_at
`

// Deactivate all themes first, then activate the specified one
func (q *Queries) ActivateTheme(ctx context.Context, id int64) (Theme, error) {
	row := q.db.QueryRowContext(ctx, activateTheme, id)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Version,
		&i.Author,
		&i.Config,
		&i.Active,
		&i.CreatedAt,
		&i.ChangedAt,
	)
	return i, err
}

const createTheme = `-- name: CreateTheme :one
INSERT INTO themes (
  name,
  slug,
  description,
  version,
  author,
  config,
  active
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
) RETURNING id, name, slug, description, version, author, config, active, created_at, changed_at
`

type CreateThemeParams struct {
	Name        string          `json:"name"`
	Slug        string          `json:"slug"`
	Description sql.NullString  `json:"description"`
	Version     string          `json:"version"`
	Author      sql.NullString  `json:"author"`
	Config      json.RawMessage `json:"config"`
	Active      bool            `json:"active"`
}

func (q *Queries) CreateTheme(ctx context.Context, arg CreateThemeParams) (Theme, error) {
	row := q.db.QueryRowContext(ctx, createTheme,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Version,
		arg.Author,
		arg.Config,
		arg.Active,
	)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Version,
		&i.Author,
		&i.Config,
		&i.Active,
		&i.CreatedAt,
		&i.ChangedAt,
	)
	return i, err
}

const deleteAllThemeSettings = `-- name: DeleteAllThemeSettings :exec
DELETE FROM theme_settings WHERE theme_id = $1
`

func (q *Queries) DeleteAllThemeSettings(ctx context.Context, themeID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAllThemeSettings, themeID)
	return err
}

const deleteTheme = `-- name: DeleteTheme :exec
DELETE FROM themes WHERE id = $1
`

func (q *Queries) DeleteTheme(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTheme, id)
	return err
}

const deleteThemeSetting = `-- name: DeleteThemeSetting :exec
DELETE FROM theme_settings 
WHERE theme_id = $1 AND setting_key = $2
`

type DeleteThemeSettingParams struct {
	ThemeID    int64  `json:"theme_id"`
	SettingKey string `json:"setting_key"`
}

func (q *Queries) DeleteThemeSetting(ctx context.Context, arg DeleteThemeSettingParams) error {
	_, err := q.db.ExecContext(ctx, deleteThemeSetting, arg.ThemeID, arg.SettingKey)
	return err
}

const getActiveTheme = `-- name: GetActiveTheme :one
SELECT id, name, slug, description, version, author, config, active, created_at, changed_at FROM themes WHERE active = true LIMIT 1
`

func (q *Queries) GetActiveTheme(ctx context.Context) (Theme, error) {
	row := q.db.QueryRowContext(ctx, getActiveTheme)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Version,
		&i.Author,
		&i.Config,
		&i.Active,
		&i.CreatedAt,
		&i.ChangedAt,
	)
	return i, err
}

const getActiveThemeWithSettings = `-- name: GetActiveThemeWithSettings :one
SELECT 
  t.id, t.name, t.slug, t.description, t.version, t.author, t.config, t.active, t.created_at, t.changed_at,
  COALESCE(
    jsonb_object_agg(ts.setting_key, ts.setting_value) FILTER (WHERE ts.id IS NOT NULL),
    '{}'::jsonb
  ) as settings
FROM themes t
LEFT JOIN theme_settings ts ON t.id = ts.theme_id
WHERE t.active = true
GROUP BY t.id
LIMIT 1
`

type GetActiveThemeWithSettingsRow struct {
	ID          int64           `json:"id"`
	Name        string          `json:"name"`
	Slug        string          `json:"slug"`
	Description sql.NullString  `json:"description"`
	Version     string          `json:"version"`
	Author      sql.NullString  `json:"author"`
	Config      json.RawMessage `json:"config"`
	Active      bool            `json:"active"`
	CreatedAt   time.Time       `json:"created_at"`
	ChangedAt   time.Time       `json:"changed_at"`
	Settings    interface{}     `json:"settings"`
}

// Get active theme with its settings
func (q *Queries) GetActiveThemeWithSettings(ctx context.Context) (GetActiveThemeWithSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveThemeWithSettings)
	var i GetActiveThemeWithSettingsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Version,
		&i.Author,
		&i.Config,
		&i.Active,
		&i.CreatedAt,
		&i.ChangedAt,
		&i.Settings,
	)
	return i, err
}

const getTheme = `-- name: GetTheme :one
SELECT id, name, slug, description, version, author, config, active, created_at, changed_at FROM themes WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTheme(ctx context.Context, id int64) (Theme, error) {
	row := q.db.QueryRowContext(ctx, getTheme, id)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Version,
		&i.Author,
		&i.Config,
		&i.Active,
		&i.CreatedAt,
		&i.ChangedAt,
	)
	return i, err
}

const getThemeBySlug = `-- name: GetThemeBySlug :one
SELECT id, name, slug, description, version, author, config, active, created_at, changed_at FROM themes WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetThemeBySlug(ctx context.Context, slug string) (Theme, error) {
	row := q.db.QueryRowContext(ctx, getThemeBySlug, slug)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Version,
		&i.Author,
		&i.Config,
		&i.Active,
		&i.CreatedAt,
		&i.ChangedAt,
	)
	return i, err
}

const getThemeSetting = `-- name: GetThemeSetting :one

SELECT id, theme_id, setting_key, setting_value, created_at, changed_at FROM theme_settings 
WHERE theme_id = $1 AND setting_key = $2 
LIMIT 1
`

type GetThemeSettingParams struct {
	ThemeID    int64  `json:"theme_id"`
	SettingKey string `json:"setting_key"`
}

// Theme Settings Queries
func (q *Queries) GetThemeSetting(ctx context.Context, arg GetThemeSettingParams) (ThemeSetting, error) {
	row := q.db.QueryRowContext(ctx, getThemeSetting, arg.ThemeID, arg.SettingKey)
	var i ThemeSetting
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.SettingKey,
		&i.SettingValue,
		&i.CreatedAt,
		&i.ChangedAt,
	)
	return i, err
}

const listThemeSettings = `-- name: ListThemeSettings :many
SELECT id, theme_id, setting_key, setting_value, created_at, changed_at FROM theme_settings
WHERE theme_id = $1
ORDER BY setting_key
`

func (q *Queries) ListThemeSettings(ctx context.Context, themeID int64) ([]ThemeSetting, error) {
	rows, err := q.db.QueryContext(ctx, listThemeSettings, themeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ThemeSetting{}
	for rows.Next() {
		var i ThemeSetting
		if err := rows.Scan(
			&i.ID,
			&i.ThemeID,
			&i.SettingKey,
			&i.SettingValue,
			&i.CreatedAt,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThemes = `-- name: ListThemes :many
SELECT id, name, slug, description, version, author, config, active, created_at, changed_at FROM themes
ORDER BY active DESC, name ASC
`

func (q *Queries) ListThemes(ctx context.Context) ([]Theme, error) {
	rows, err := q.db.QueryContext(ctx, listThemes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Theme{}
	for rows.Next() {
		var i Theme
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Version,
			&i.Author,
			&i.Config,
			&i.Active,
			&i.CreatedAt,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTheme = `-- name: UpdateTheme :one
UPDATE themes
SET 
  name = COALESCE($1, name),
  description = COALESCE($2, description),
  version = COALESCE($3, version),
  author = COALESCE($4, author),
  config = COALESCE($5, config),
  changed_at = now()
WHERE themes.id = $6
RETURNING id, name, slug, description, version, author, config, active, created_at, changed_at
`

type UpdateThemeParams struct {
	Name        sql.NullString        `json:"name"`
	Description sql.NullString        `json:"description"`
	Version     sql.NullString        `json:"version"`
	Author      sql.NullString        `json:"author"`
	Config      pqtype.NullRawMessage `json:"config"`
	ID          int64                 `json:"id"`
}

func (q *Queries) UpdateTheme(ctx context.Context, arg UpdateThemeParams) (Theme, error) {
	row := q.db.QueryRowContext(ctx, updateTheme,
		arg.Name,
		arg.Description,
		arg.Version,
		arg.Author,
		arg.Config,
		arg.ID,
	)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Version,
		&i.Author,
		&i.Config,
		&i.Active,
		&i.CreatedAt,
		&i.ChangedAt,
	)
	return i, err
}

const upsertThemeSetting = `-- name: UpsertThemeSetting :one
INSERT INTO theme_settings (theme_id, setting_key, setting_value)
VALUES ($1, $2, $3)
ON CONFLICT (theme_id, setting_key) DO UPDATE
SET setting_value = EXCLUDED.setting_value,
    changed_at = now()
RETURNING id, theme_id, setting_key, setting_value, created_at, changed_at
`

type UpsertThemeSettingParams struct {
	ThemeID      int64           `json:"theme_id"`
	SettingKey   string          `json:"setting_key"`
	SettingValue json.RawMessage `json:"setting_value"`
}

func (q *Queries) UpsertThemeSetting(ctx context.Context, arg UpsertThemeSettingParams) (ThemeSetting, error) {
	row := q.db.QueryRowContext(ctx, upsertThemeSetting, arg.ThemeID, arg.SettingKey, arg.SettingValue)
	var i ThemeSetting
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.SettingKey,
		&i.SettingValue,
		&i.CreatedAt,
		&i.ChangedAt,
	)
	return i, err
}
