// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-live-cms/go-live-cms/db/sqlc (interfaces: Store)

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	db "github.com/go-live-cms/go-live-cms/db/sqlc"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AddPostToTaxonomyTerm mocks base method.
func (m *MockStore) AddPostToTaxonomyTerm(arg0 context.Context, arg1 db.AddPostToTaxonomyTermParams) (db.PostTaxonomyRelationship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPostToTaxonomyTerm", arg0, arg1)
	ret0, _ := ret[0].(db.PostTaxonomyRelationship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPostToTaxonomyTerm indicates an expected call of AddPostToTaxonomyTerm.
func (mr *MockStoreMockRecorder) AddPostToTaxonomyTerm(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPostToTaxonomyTerm", reflect.TypeOf((*MockStore)(nil).AddPostToTaxonomyTerm), arg0, arg1)
}

// BlockAllSessionsForUser mocks base method.
func (m *MockStore) BlockAllSessionsForUser(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockAllSessionsForUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// BlockAllSessionsForUser indicates an expected call of BlockAllSessionsForUser.
func (mr *MockStoreMockRecorder) BlockAllSessionsForUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockAllSessionsForUser", reflect.TypeOf((*MockStore)(nil).BlockAllSessionsForUser), arg0, arg1)
}

// BlockSession mocks base method.
func (m *MockStore) BlockSession(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockSession", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// BlockSession indicates an expected call of BlockSession.
func (mr *MockStoreMockRecorder) BlockSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockSession", reflect.TypeOf((*MockStore)(nil).BlockSession), arg0, arg1)
}

// CountFilteredPosts mocks base method.
func (m *MockStore) CountFilteredPosts(arg0 context.Context, arg1 db.CountFilteredPostsParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFilteredPosts", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFilteredPosts indicates an expected call of CountFilteredPosts.
func (mr *MockStoreMockRecorder) CountFilteredPosts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFilteredPosts", reflect.TypeOf((*MockStore)(nil).CountFilteredPosts), arg0, arg1)
}

// CountPostsByTaxonomyTerm mocks base method.
func (m *MockStore) CountPostsByTaxonomyTerm(arg0 context.Context, arg1 int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPostsByTaxonomyTerm", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPostsByTaxonomyTerm indicates an expected call of CountPostsByTaxonomyTerm.
func (mr *MockStoreMockRecorder) CountPostsByTaxonomyTerm(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPostsByTaxonomyTerm", reflect.TypeOf((*MockStore)(nil).CountPostsByTaxonomyTerm), arg0, arg1)
}

// CountPostsByType mocks base method.
func (m *MockStore) CountPostsByType(arg0 context.Context, arg1 string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPostsByType", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPostsByType indicates an expected call of CountPostsByType.
func (mr *MockStoreMockRecorder) CountPostsByType(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPostsByType", reflect.TypeOf((*MockStore)(nil).CountPostsByType), arg0, arg1)
}

// CountPostsByTypeFiltered mocks base method.
func (m *MockStore) CountPostsByTypeFiltered(arg0 context.Context, arg1 db.CountPostsByTypeFilteredParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPostsByTypeFiltered", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPostsByTypeFiltered indicates an expected call of CountPostsByTypeFiltered.
func (mr *MockStoreMockRecorder) CountPostsByTypeFiltered(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPostsByTypeFiltered", reflect.TypeOf((*MockStore)(nil).CountPostsByTypeFiltered), arg0, arg1)
}

// CountTaxonomyTerms mocks base method.
func (m *MockStore) CountTaxonomyTerms(arg0 context.Context, arg1 string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTaxonomyTerms", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTaxonomyTerms indicates an expected call of CountTaxonomyTerms.
func (mr *MockStoreMockRecorder) CountTaxonomyTerms(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTaxonomyTerms", reflect.TypeOf((*MockStore)(nil).CountTaxonomyTerms), arg0, arg1)
}

// CountTotalMedia mocks base method.
func (m *MockStore) CountTotalMedia(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTotalMedia", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTotalMedia indicates an expected call of CountTotalMedia.
func (mr *MockStoreMockRecorder) CountTotalMedia(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTotalMedia", reflect.TypeOf((*MockStore)(nil).CountTotalMedia), arg0)
}

// CountTotalPosts mocks base method.
func (m *MockStore) CountTotalPosts(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTotalPosts", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTotalPosts indicates an expected call of CountTotalPosts.
func (mr *MockStoreMockRecorder) CountTotalPosts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTotalPosts", reflect.TypeOf((*MockStore)(nil).CountTotalPosts), arg0)
}

// CountTotalSessions mocks base method.
func (m *MockStore) CountTotalSessions(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTotalSessions", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTotalSessions indicates an expected call of CountTotalSessions.
func (mr *MockStoreMockRecorder) CountTotalSessions(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTotalSessions", reflect.TypeOf((*MockStore)(nil).CountTotalSessions), arg0)
}

// CountTotalUsers mocks base method.
func (m *MockStore) CountTotalUsers(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTotalUsers", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTotalUsers indicates an expected call of CountTotalUsers.
func (mr *MockStoreMockRecorder) CountTotalUsers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTotalUsers", reflect.TypeOf((*MockStore)(nil).CountTotalUsers), arg0)
}

// CreateMedia mocks base method.
func (m *MockStore) CreateMedia(arg0 context.Context, arg1 db.CreateMediaParams) (db.Medium, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMedia", arg0, arg1)
	ret0, _ := ret[0].(db.Medium)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMedia indicates an expected call of CreateMedia.
func (mr *MockStoreMockRecorder) CreateMedia(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMedia", reflect.TypeOf((*MockStore)(nil).CreateMedia), arg0, arg1)
}

// CreateMediaAndLinkTx mocks base method.
func (m *MockStore) CreateMediaAndLinkTx(arg0 context.Context, arg1 db.CreateMediaAndLinkTxParams) (db.CreateMediaAndLinkTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMediaAndLinkTx", arg0, arg1)
	ret0, _ := ret[0].(db.CreateMediaAndLinkTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMediaAndLinkTx indicates an expected call of CreateMediaAndLinkTx.
func (mr *MockStoreMockRecorder) CreateMediaAndLinkTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMediaAndLinkTx", reflect.TypeOf((*MockStore)(nil).CreateMediaAndLinkTx), arg0, arg1)
}

// CreatePostMedia mocks base method.
func (m *MockStore) CreatePostMedia(arg0 context.Context, arg1 db.CreatePostMediaParams) (db.PostMedium, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePostMedia", arg0, arg1)
	ret0, _ := ret[0].(db.PostMedium)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePostMedia indicates an expected call of CreatePostMedia.
func (mr *MockStoreMockRecorder) CreatePostMedia(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePostMedia", reflect.TypeOf((*MockStore)(nil).CreatePostMedia), arg0, arg1)
}

// CreatePostMeta mocks base method.
func (m *MockStore) CreatePostMeta(arg0 context.Context, arg1 db.CreatePostMetaParams) (db.PostMetum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePostMeta", arg0, arg1)
	ret0, _ := ret[0].(db.PostMetum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePostMeta indicates an expected call of CreatePostMeta.
func (mr *MockStoreMockRecorder) CreatePostMeta(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePostMeta", reflect.TypeOf((*MockStore)(nil).CreatePostMeta), arg0, arg1)
}

// CreatePostTx mocks base method.
func (m *MockStore) CreatePostTx(arg0 context.Context, arg1 db.CreatePostTxParams) (db.CreatePostTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePostTx", arg0, arg1)
	ret0, _ := ret[0].(db.CreatePostTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePostTx indicates an expected call of CreatePostTx.
func (mr *MockStoreMockRecorder) CreatePostTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePostTx", reflect.TypeOf((*MockStore)(nil).CreatePostTx), arg0, arg1)
}

// CreatePostType mocks base method.
func (m *MockStore) CreatePostType(arg0 context.Context, arg1 db.CreatePostTypeParams) (db.PostType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePostType", arg0, arg1)
	ret0, _ := ret[0].(db.PostType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePostType indicates an expected call of CreatePostType.
func (mr *MockStoreMockRecorder) CreatePostType(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePostType", reflect.TypeOf((*MockStore)(nil).CreatePostType), arg0, arg1)
}

// CreatePostWithMediaTx mocks base method.
func (m *MockStore) CreatePostWithMediaTx(arg0 context.Context, arg1 db.CreatePostWithMediaTxParams) (db.CreatePostWithMediaTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePostWithMediaTx", arg0, arg1)
	ret0, _ := ret[0].(db.CreatePostWithMediaTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePostWithMediaTx indicates an expected call of CreatePostWithMediaTx.
func (mr *MockStoreMockRecorder) CreatePostWithMediaTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePostWithMediaTx", reflect.TypeOf((*MockStore)(nil).CreatePostWithMediaTx), arg0, arg1)
}

// CreatePostWithTaxonomyTermsTx mocks base method.
func (m *MockStore) CreatePostWithTaxonomyTermsTx(arg0 context.Context, arg1 db.CreatePostWithTaxonomyTermsTxParams) (db.CreatePostWithTaxonomyTermsTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePostWithTaxonomyTermsTx", arg0, arg1)
	ret0, _ := ret[0].(db.CreatePostWithTaxonomyTermsTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePostWithTaxonomyTermsTx indicates an expected call of CreatePostWithTaxonomyTermsTx.
func (mr *MockStoreMockRecorder) CreatePostWithTaxonomyTermsTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePostWithTaxonomyTermsTx", reflect.TypeOf((*MockStore)(nil).CreatePostWithTaxonomyTermsTx), arg0, arg1)
}

// CreatePosts mocks base method.
func (m *MockStore) CreatePosts(arg0 context.Context, arg1 db.CreatePostsParams) (db.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePosts", arg0, arg1)
	ret0, _ := ret[0].(db.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePosts indicates an expected call of CreatePosts.
func (mr *MockStoreMockRecorder) CreatePosts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePosts", reflect.TypeOf((*MockStore)(nil).CreatePosts), arg0, arg1)
}

// CreateSession mocks base method.
func (m *MockStore) CreateSession(arg0 context.Context, arg1 db.CreateSessionParams) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", arg0, arg1)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockStoreMockRecorder) CreateSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockStore)(nil).CreateSession), arg0, arg1)
}

// CreateTaxonomyTerm mocks base method.
func (m *MockStore) CreateTaxonomyTerm(arg0 context.Context, arg1 db.CreateTaxonomyTermParams) (db.TaxonomyTerm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTaxonomyTerm", arg0, arg1)
	ret0, _ := ret[0].(db.TaxonomyTerm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTaxonomyTerm indicates an expected call of CreateTaxonomyTerm.
func (mr *MockStoreMockRecorder) CreateTaxonomyTerm(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTaxonomyTerm", reflect.TypeOf((*MockStore)(nil).CreateTaxonomyTerm), arg0, arg1)
}

// CreateTaxonomyTermAndLinkTx mocks base method.
func (m *MockStore) CreateTaxonomyTermAndLinkTx(arg0 context.Context, arg1 db.CreateTaxonomyTermAndLinkTxParams) (db.CreateTaxonomyTermAndLinkTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTaxonomyTermAndLinkTx", arg0, arg1)
	ret0, _ := ret[0].(db.CreateTaxonomyTermAndLinkTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTaxonomyTermAndLinkTx indicates an expected call of CreateTaxonomyTermAndLinkTx.
func (mr *MockStoreMockRecorder) CreateTaxonomyTermAndLinkTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTaxonomyTermAndLinkTx", reflect.TypeOf((*MockStore)(nil).CreateTaxonomyTermAndLinkTx), arg0, arg1)
}

// CreateTaxonomyType mocks base method.
func (m *MockStore) CreateTaxonomyType(arg0 context.Context, arg1 db.CreateTaxonomyTypeParams) (db.TaxonomyType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTaxonomyType", arg0, arg1)
	ret0, _ := ret[0].(db.TaxonomyType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTaxonomyType indicates an expected call of CreateTaxonomyType.
func (mr *MockStoreMockRecorder) CreateTaxonomyType(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTaxonomyType", reflect.TypeOf((*MockStore)(nil).CreateTaxonomyType), arg0, arg1)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(arg0 context.Context, arg1 db.CreateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), arg0, arg1)
}

// CreateUserPost mocks base method.
func (m *MockStore) CreateUserPost(arg0 context.Context, arg1 db.CreateUserPostParams) (db.UserPost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserPost", arg0, arg1)
	ret0, _ := ret[0].(db.UserPost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserPost indicates an expected call of CreateUserPost.
func (mr *MockStoreMockRecorder) CreateUserPost(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserPost", reflect.TypeOf((*MockStore)(nil).CreateUserPost), arg0, arg1)
}

// DeleteAllPostMeta mocks base method.
func (m *MockStore) DeleteAllPostMeta(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllPostMeta", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllPostMeta indicates an expected call of DeleteAllPostMeta.
func (mr *MockStoreMockRecorder) DeleteAllPostMeta(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllPostMeta", reflect.TypeOf((*MockStore)(nil).DeleteAllPostMeta), arg0, arg1)
}

// DeleteMedia mocks base method.
func (m *MockStore) DeleteMedia(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMedia", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMedia indicates an expected call of DeleteMedia.
func (mr *MockStoreMockRecorder) DeleteMedia(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMedia", reflect.TypeOf((*MockStore)(nil).DeleteMedia), arg0, arg1)
}

// DeleteMediaByUserID mocks base method.
func (m *MockStore) DeleteMediaByUserID(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMediaByUserID", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMediaByUserID indicates an expected call of DeleteMediaByUserID.
func (mr *MockStoreMockRecorder) DeleteMediaByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMediaByUserID", reflect.TypeOf((*MockStore)(nil).DeleteMediaByUserID), arg0, arg1)
}

// DeleteMediaPosts mocks base method.
func (m *MockStore) DeleteMediaPosts(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMediaPosts", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMediaPosts indicates an expected call of DeleteMediaPosts.
func (mr *MockStoreMockRecorder) DeleteMediaPosts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMediaPosts", reflect.TypeOf((*MockStore)(nil).DeleteMediaPosts), arg0, arg1)
}

// DeleteMediaTx mocks base method.
func (m *MockStore) DeleteMediaTx(arg0 context.Context, arg1 db.DeleteMediaTxParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMediaTx", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMediaTx indicates an expected call of DeleteMediaTx.
func (mr *MockStoreMockRecorder) DeleteMediaTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMediaTx", reflect.TypeOf((*MockStore)(nil).DeleteMediaTx), arg0, arg1)
}

// DeletePost mocks base method.
func (m *MockStore) DeletePost(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePost", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePost indicates an expected call of DeletePost.
func (mr *MockStoreMockRecorder) DeletePost(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePost", reflect.TypeOf((*MockStore)(nil).DeletePost), arg0, arg1)
}

// DeletePostMedia mocks base method.
func (m *MockStore) DeletePostMedia(arg0 context.Context, arg1 db.DeletePostMediaParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePostMedia", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePostMedia indicates an expected call of DeletePostMedia.
func (mr *MockStoreMockRecorder) DeletePostMedia(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePostMedia", reflect.TypeOf((*MockStore)(nil).DeletePostMedia), arg0, arg1)
}

// DeletePostMediaByOrder mocks base method.
func (m *MockStore) DeletePostMediaByOrder(arg0 context.Context, arg1 db.DeletePostMediaByOrderParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePostMediaByOrder", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePostMediaByOrder indicates an expected call of DeletePostMediaByOrder.
func (mr *MockStoreMockRecorder) DeletePostMediaByOrder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePostMediaByOrder", reflect.TypeOf((*MockStore)(nil).DeletePostMediaByOrder), arg0, arg1)
}

// DeletePostMedias mocks base method.
func (m *MockStore) DeletePostMedias(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePostMedias", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePostMedias indicates an expected call of DeletePostMedias.
func (mr *MockStoreMockRecorder) DeletePostMedias(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePostMedias", reflect.TypeOf((*MockStore)(nil).DeletePostMedias), arg0, arg1)
}

// DeletePostMeta mocks base method.
func (m *MockStore) DeletePostMeta(arg0 context.Context, arg1 db.DeletePostMetaParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePostMeta", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePostMeta indicates an expected call of DeletePostMeta.
func (mr *MockStoreMockRecorder) DeletePostMeta(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePostMeta", reflect.TypeOf((*MockStore)(nil).DeletePostMeta), arg0, arg1)
}

// DeletePostTx mocks base method.
func (m *MockStore) DeletePostTx(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePostTx", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePostTx indicates an expected call of DeletePostTx.
func (mr *MockStoreMockRecorder) DeletePostTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePostTx", reflect.TypeOf((*MockStore)(nil).DeletePostTx), arg0, arg1)
}

// DeletePostType mocks base method.
func (m *MockStore) DeletePostType(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePostType", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePostType indicates an expected call of DeletePostType.
func (mr *MockStoreMockRecorder) DeletePostType(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePostType", reflect.TypeOf((*MockStore)(nil).DeletePostType), arg0, arg1)
}

// DeletePostsByUserID mocks base method.
func (m *MockStore) DeletePostsByUserID(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePostsByUserID", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePostsByUserID indicates an expected call of DeletePostsByUserID.
func (mr *MockStoreMockRecorder) DeletePostsByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePostsByUserID", reflect.TypeOf((*MockStore)(nil).DeletePostsByUserID), arg0, arg1)
}

// DeleteTaxonomyTerm mocks base method.
func (m *MockStore) DeleteTaxonomyTerm(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTaxonomyTerm", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTaxonomyTerm indicates an expected call of DeleteTaxonomyTerm.
func (mr *MockStoreMockRecorder) DeleteTaxonomyTerm(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTaxonomyTerm", reflect.TypeOf((*MockStore)(nil).DeleteTaxonomyTerm), arg0, arg1)
}

// DeleteTaxonomyTermTx mocks base method.
func (m *MockStore) DeleteTaxonomyTermTx(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTaxonomyTermTx", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTaxonomyTermTx indicates an expected call of DeleteTaxonomyTermTx.
func (mr *MockStoreMockRecorder) DeleteTaxonomyTermTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTaxonomyTermTx", reflect.TypeOf((*MockStore)(nil).DeleteTaxonomyTermTx), arg0, arg1)
}

// DeleteTaxonomyType mocks base method.
func (m *MockStore) DeleteTaxonomyType(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTaxonomyType", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTaxonomyType indicates an expected call of DeleteTaxonomyType.
func (mr *MockStoreMockRecorder) DeleteTaxonomyType(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTaxonomyType", reflect.TypeOf((*MockStore)(nil).DeleteTaxonomyType), arg0, arg1)
}

// DeleteUser mocks base method.
func (m *MockStore) DeleteUser(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockStoreMockRecorder) DeleteUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockStore)(nil).DeleteUser), arg0, arg1)
}

// DeleteUserPost mocks base method.
func (m *MockStore) DeleteUserPost(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserPost", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserPost indicates an expected call of DeleteUserPost.
func (mr *MockStoreMockRecorder) DeleteUserPost(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserPost", reflect.TypeOf((*MockStore)(nil).DeleteUserPost), arg0, arg1)
}

// DeleteUserPostsByUserID mocks base method.
func (m *MockStore) DeleteUserPostsByUserID(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserPostsByUserID", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserPostsByUserID indicates an expected call of DeleteUserPostsByUserID.
func (mr *MockStoreMockRecorder) DeleteUserPostsByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserPostsByUserID", reflect.TypeOf((*MockStore)(nil).DeleteUserPostsByUserID), arg0, arg1)
}

// DeleteUserSessions mocks base method.
func (m *MockStore) DeleteUserSessions(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserSessions", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserSessions indicates an expected call of DeleteUserSessions.
func (mr *MockStoreMockRecorder) DeleteUserSessions(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserSessions", reflect.TypeOf((*MockStore)(nil).DeleteUserSessions), arg0, arg1)
}

// DeleteUserTx mocks base method.
func (m *MockStore) DeleteUserTx(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserTx", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserTx indicates an expected call of DeleteUserTx.
func (mr *MockStoreMockRecorder) DeleteUserTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserTx", reflect.TypeOf((*MockStore)(nil).DeleteUserTx), arg0, arg1)
}

// DeleteUserWithTransferTx mocks base method.
func (m *MockStore) DeleteUserWithTransferTx(arg0 context.Context, arg1 db.DeleteUserWithTransferTxParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserWithTransferTx", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserWithTransferTx indicates an expected call of DeleteUserWithTransferTx.
func (mr *MockStoreMockRecorder) DeleteUserWithTransferTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserWithTransferTx", reflect.TypeOf((*MockStore)(nil).DeleteUserWithTransferTx), arg0, arg1)
}

// ExecTx mocks base method.
func (m *MockStore) ExecTx(arg0 context.Context, arg1 func(*db.Queries) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecTx", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecTx indicates an expected call of ExecTx.
func (mr *MockStoreMockRecorder) ExecTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecTx", reflect.TypeOf((*MockStore)(nil).ExecTx), arg0, arg1)
}

// GetFeaturedImage mocks base method.
func (m *MockStore) GetFeaturedImage(arg0 context.Context, arg1 int64) (db.GetFeaturedImageRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeaturedImage", arg0, arg1)
	ret0, _ := ret[0].(db.GetFeaturedImageRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeaturedImage indicates an expected call of GetFeaturedImage.
func (mr *MockStoreMockRecorder) GetFeaturedImage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeaturedImage", reflect.TypeOf((*MockStore)(nil).GetFeaturedImage), arg0, arg1)
}

// GetMedia mocks base method.
func (m *MockStore) GetMedia(arg0 context.Context, arg1 int64) (db.Medium, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMedia", arg0, arg1)
	ret0, _ := ret[0].(db.Medium)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMedia indicates an expected call of GetMedia.
func (mr *MockStoreMockRecorder) GetMedia(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMedia", reflect.TypeOf((*MockStore)(nil).GetMedia), arg0, arg1)
}

// GetMediaByPost mocks base method.
func (m *MockStore) GetMediaByPost(arg0 context.Context, arg1 int64) ([]db.Medium, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaByPost", arg0, arg1)
	ret0, _ := ret[0].([]db.Medium)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaByPost indicates an expected call of GetMediaByPost.
func (mr *MockStoreMockRecorder) GetMediaByPost(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaByPost", reflect.TypeOf((*MockStore)(nil).GetMediaByPost), arg0, arg1)
}

// GetMediaByUser mocks base method.
func (m *MockStore) GetMediaByUser(arg0 context.Context, arg1 db.GetMediaByUserParams) ([]db.GetMediaByUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaByUser", arg0, arg1)
	ret0, _ := ret[0].([]db.GetMediaByUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaByUser indicates an expected call of GetMediaByUser.
func (mr *MockStoreMockRecorder) GetMediaByUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaByUser", reflect.TypeOf((*MockStore)(nil).GetMediaByUser), arg0, arg1)
}

// GetMediaPostCount mocks base method.
func (m *MockStore) GetMediaPostCount(arg0 context.Context, arg1 int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaPostCount", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaPostCount indicates an expected call of GetMediaPostCount.
func (mr *MockStoreMockRecorder) GetMediaPostCount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaPostCount", reflect.TypeOf((*MockStore)(nil).GetMediaPostCount), arg0, arg1)
}

// GetPopularMedia mocks base method.
func (m *MockStore) GetPopularMedia(arg0 context.Context, arg1 int32) ([]db.GetPopularMediaRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPopularMedia", arg0, arg1)
	ret0, _ := ret[0].([]db.GetPopularMediaRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPopularMedia indicates an expected call of GetPopularMedia.
func (mr *MockStoreMockRecorder) GetPopularMedia(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPopularMedia", reflect.TypeOf((*MockStore)(nil).GetPopularMedia), arg0, arg1)
}

// GetPopularTaxonomyTerms mocks base method.
func (m *MockStore) GetPopularTaxonomyTerms(arg0 context.Context, arg1 db.GetPopularTaxonomyTermsParams) ([]db.GetPopularTaxonomyTermsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPopularTaxonomyTerms", arg0, arg1)
	ret0, _ := ret[0].([]db.GetPopularTaxonomyTermsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPopularTaxonomyTerms indicates an expected call of GetPopularTaxonomyTerms.
func (mr *MockStoreMockRecorder) GetPopularTaxonomyTerms(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPopularTaxonomyTerms", reflect.TypeOf((*MockStore)(nil).GetPopularTaxonomyTerms), arg0, arg1)
}

// GetPost mocks base method.
func (m *MockStore) GetPost(arg0 context.Context, arg1 int64) (db.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPost", arg0, arg1)
	ret0, _ := ret[0].(db.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPost indicates an expected call of GetPost.
func (mr *MockStoreMockRecorder) GetPost(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPost", reflect.TypeOf((*MockStore)(nil).GetPost), arg0, arg1)
}

// GetPostChildren mocks base method.
func (m *MockStore) GetPostChildren(arg0 context.Context, arg1 sql.NullInt64) ([]db.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostChildren", arg0, arg1)
	ret0, _ := ret[0].([]db.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostChildren indicates an expected call of GetPostChildren.
func (mr *MockStoreMockRecorder) GetPostChildren(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostChildren", reflect.TypeOf((*MockStore)(nil).GetPostChildren), arg0, arg1)
}

// GetPostMedia mocks base method.
func (m *MockStore) GetPostMedia(arg0 context.Context, arg1 int64) ([]db.GetPostMediaRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostMedia", arg0, arg1)
	ret0, _ := ret[0].([]db.GetPostMediaRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostMedia indicates an expected call of GetPostMedia.
func (mr *MockStoreMockRecorder) GetPostMedia(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostMedia", reflect.TypeOf((*MockStore)(nil).GetPostMedia), arg0, arg1)
}

// GetPostMediaCount mocks base method.
func (m *MockStore) GetPostMediaCount(arg0 context.Context, arg1 int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostMediaCount", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostMediaCount indicates an expected call of GetPostMediaCount.
func (mr *MockStoreMockRecorder) GetPostMediaCount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostMediaCount", reflect.TypeOf((*MockStore)(nil).GetPostMediaCount), arg0, arg1)
}

// GetPostMeta mocks base method.
func (m *MockStore) GetPostMeta(arg0 context.Context, arg1 int64) ([]db.PostMetum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostMeta", arg0, arg1)
	ret0, _ := ret[0].([]db.PostMetum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostMeta indicates an expected call of GetPostMeta.
func (mr *MockStoreMockRecorder) GetPostMeta(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostMeta", reflect.TypeOf((*MockStore)(nil).GetPostMeta), arg0, arg1)
}

// GetPostMetaByKey mocks base method.
func (m *MockStore) GetPostMetaByKey(arg0 context.Context, arg1 db.GetPostMetaByKeyParams) (db.PostMetum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostMetaByKey", arg0, arg1)
	ret0, _ := ret[0].(db.PostMetum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostMetaByKey indicates an expected call of GetPostMetaByKey.
func (mr *MockStoreMockRecorder) GetPostMetaByKey(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostMetaByKey", reflect.TypeOf((*MockStore)(nil).GetPostMetaByKey), arg0, arg1)
}

// GetPostTaxonomyTerms mocks base method.
func (m *MockStore) GetPostTaxonomyTerms(arg0 context.Context, arg1 int64) ([]db.GetPostTaxonomyTermsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostTaxonomyTerms", arg0, arg1)
	ret0, _ := ret[0].([]db.GetPostTaxonomyTermsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostTaxonomyTerms indicates an expected call of GetPostTaxonomyTerms.
func (mr *MockStoreMockRecorder) GetPostTaxonomyTerms(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostTaxonomyTerms", reflect.TypeOf((*MockStore)(nil).GetPostTaxonomyTerms), arg0, arg1)
}

// GetPostType mocks base method.
func (m *MockStore) GetPostType(arg0 context.Context, arg1 string) (db.PostType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostType", arg0, arg1)
	ret0, _ := ret[0].(db.PostType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostType indicates an expected call of GetPostType.
func (mr *MockStoreMockRecorder) GetPostType(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostType", reflect.TypeOf((*MockStore)(nil).GetPostType), arg0, arg1)
}

// GetPostTypeByID mocks base method.
func (m *MockStore) GetPostTypeByID(arg0 context.Context, arg1 int64) (db.PostType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostTypeByID", arg0, arg1)
	ret0, _ := ret[0].(db.PostType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostTypeByID indicates an expected call of GetPostTypeByID.
func (mr *MockStoreMockRecorder) GetPostTypeByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostTypeByID", reflect.TypeOf((*MockStore)(nil).GetPostTypeByID), arg0, arg1)
}

// GetPostWithMedia mocks base method.
func (m *MockStore) GetPostWithMedia(arg0 context.Context, arg1 int64) (db.GetPostWithMediaRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostWithMedia", arg0, arg1)
	ret0, _ := ret[0].(db.GetPostWithMediaRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostWithMedia indicates an expected call of GetPostWithMedia.
func (mr *MockStoreMockRecorder) GetPostWithMedia(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostWithMedia", reflect.TypeOf((*MockStore)(nil).GetPostWithMedia), arg0, arg1)
}

// GetPostWithMeta mocks base method.
func (m *MockStore) GetPostWithMeta(arg0 context.Context, arg1 int64) (db.GetPostWithMetaRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostWithMeta", arg0, arg1)
	ret0, _ := ret[0].(db.GetPostWithMetaRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostWithMeta indicates an expected call of GetPostWithMeta.
func (mr *MockStoreMockRecorder) GetPostWithMeta(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostWithMeta", reflect.TypeOf((*MockStore)(nil).GetPostWithMeta), arg0, arg1)
}

// GetPostsByMedia mocks base method.
func (m *MockStore) GetPostsByMedia(arg0 context.Context, arg1 int64) ([]db.GetPostsByMediaRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostsByMedia", arg0, arg1)
	ret0, _ := ret[0].([]db.GetPostsByMediaRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostsByMedia indicates an expected call of GetPostsByMedia.
func (mr *MockStoreMockRecorder) GetPostsByMedia(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostsByMedia", reflect.TypeOf((*MockStore)(nil).GetPostsByMedia), arg0, arg1)
}

// GetPostsByMultipleTaxonomyTerms mocks base method.
func (m *MockStore) GetPostsByMultipleTaxonomyTerms(arg0 context.Context, arg1 db.GetPostsByMultipleTaxonomyTermsParams) ([]db.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostsByMultipleTaxonomyTerms", arg0, arg1)
	ret0, _ := ret[0].([]db.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostsByMultipleTaxonomyTerms indicates an expected call of GetPostsByMultipleTaxonomyTerms.
func (mr *MockStoreMockRecorder) GetPostsByMultipleTaxonomyTerms(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostsByMultipleTaxonomyTerms", reflect.TypeOf((*MockStore)(nil).GetPostsByMultipleTaxonomyTerms), arg0, arg1)
}

// GetPostsByTaxonomyTerm mocks base method.
func (m *MockStore) GetPostsByTaxonomyTerm(arg0 context.Context, arg1 db.GetPostsByTaxonomyTermParams) ([]db.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostsByTaxonomyTerm", arg0, arg1)
	ret0, _ := ret[0].([]db.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostsByTaxonomyTerm indicates an expected call of GetPostsByTaxonomyTerm.
func (mr *MockStoreMockRecorder) GetPostsByTaxonomyTerm(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostsByTaxonomyTerm", reflect.TypeOf((*MockStore)(nil).GetPostsByTaxonomyTerm), arg0, arg1)
}

// GetPostsByUserWithMedia mocks base method.
func (m *MockStore) GetPostsByUserWithMedia(arg0 context.Context, arg1 db.GetPostsByUserWithMediaParams) ([]db.GetPostsByUserWithMediaRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostsByUserWithMedia", arg0, arg1)
	ret0, _ := ret[0].([]db.GetPostsByUserWithMediaRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostsByUserWithMedia indicates an expected call of GetPostsByUserWithMedia.
func (mr *MockStoreMockRecorder) GetPostsByUserWithMedia(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostsByUserWithMedia", reflect.TypeOf((*MockStore)(nil).GetPostsByUserWithMedia), arg0, arg1)
}

// GetSession mocks base method.
func (m *MockStore) GetSession(arg0 context.Context, arg1 uuid.UUID) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", arg0, arg1)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockStoreMockRecorder) GetSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockStore)(nil).GetSession), arg0, arg1)
}

// GetSessionByRefreshTokenHash mocks base method.
func (m *MockStore) GetSessionByRefreshTokenHash(arg0 context.Context, arg1 []byte) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByRefreshTokenHash", arg0, arg1)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByRefreshTokenHash indicates an expected call of GetSessionByRefreshTokenHash.
func (mr *MockStoreMockRecorder) GetSessionByRefreshTokenHash(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByRefreshTokenHash", reflect.TypeOf((*MockStore)(nil).GetSessionByRefreshTokenHash), arg0, arg1)
}

// GetTaxonomyTerm mocks base method.
func (m *MockStore) GetTaxonomyTerm(arg0 context.Context, arg1 int64) (db.TaxonomyTerm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaxonomyTerm", arg0, arg1)
	ret0, _ := ret[0].(db.TaxonomyTerm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaxonomyTerm indicates an expected call of GetTaxonomyTerm.
func (mr *MockStoreMockRecorder) GetTaxonomyTerm(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaxonomyTerm", reflect.TypeOf((*MockStore)(nil).GetTaxonomyTerm), arg0, arg1)
}

// GetTaxonomyTermBySlug mocks base method.
func (m *MockStore) GetTaxonomyTermBySlug(arg0 context.Context, arg1 string) (db.GetTaxonomyTermBySlugRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaxonomyTermBySlug", arg0, arg1)
	ret0, _ := ret[0].(db.GetTaxonomyTermBySlugRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaxonomyTermBySlug indicates an expected call of GetTaxonomyTermBySlug.
func (mr *MockStoreMockRecorder) GetTaxonomyTermBySlug(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaxonomyTermBySlug", reflect.TypeOf((*MockStore)(nil).GetTaxonomyTermBySlug), arg0, arg1)
}

// GetTaxonomyTermTree mocks base method.
func (m *MockStore) GetTaxonomyTermTree(arg0 context.Context, arg1 string) ([]db.GetTaxonomyTermTreeRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaxonomyTermTree", arg0, arg1)
	ret0, _ := ret[0].([]db.GetTaxonomyTermTreeRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaxonomyTermTree indicates an expected call of GetTaxonomyTermTree.
func (mr *MockStoreMockRecorder) GetTaxonomyTermTree(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaxonomyTermTree", reflect.TypeOf((*MockStore)(nil).GetTaxonomyTermTree), arg0, arg1)
}

// GetTaxonomyTermsWithPostCount mocks base method.
func (m *MockStore) GetTaxonomyTermsWithPostCount(arg0 context.Context, arg1 db.GetTaxonomyTermsWithPostCountParams) ([]db.GetTaxonomyTermsWithPostCountRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaxonomyTermsWithPostCount", arg0, arg1)
	ret0, _ := ret[0].([]db.GetTaxonomyTermsWithPostCountRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaxonomyTermsWithPostCount indicates an expected call of GetTaxonomyTermsWithPostCount.
func (mr *MockStoreMockRecorder) GetTaxonomyTermsWithPostCount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaxonomyTermsWithPostCount", reflect.TypeOf((*MockStore)(nil).GetTaxonomyTermsWithPostCount), arg0, arg1)
}

// GetTaxonomyType mocks base method.
func (m *MockStore) GetTaxonomyType(arg0 context.Context, arg1 string) (db.TaxonomyType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaxonomyType", arg0, arg1)
	ret0, _ := ret[0].(db.TaxonomyType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaxonomyType indicates an expected call of GetTaxonomyType.
func (mr *MockStoreMockRecorder) GetTaxonomyType(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaxonomyType", reflect.TypeOf((*MockStore)(nil).GetTaxonomyType), arg0, arg1)
}

// GetTaxonomyTypeByID mocks base method.
func (m *MockStore) GetTaxonomyTypeByID(arg0 context.Context, arg1 int64) (db.TaxonomyType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaxonomyTypeByID", arg0, arg1)
	ret0, _ := ret[0].(db.TaxonomyType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaxonomyTypeByID indicates an expected call of GetTaxonomyTypeByID.
func (mr *MockStoreMockRecorder) GetTaxonomyTypeByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaxonomyTypeByID", reflect.TypeOf((*MockStore)(nil).GetTaxonomyTypeByID), arg0, arg1)
}

// GetTermChildren mocks base method.
func (m *MockStore) GetTermChildren(arg0 context.Context, arg1 sql.NullInt64) ([]db.TaxonomyTerm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTermChildren", arg0, arg1)
	ret0, _ := ret[0].([]db.TaxonomyTerm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTermChildren indicates an expected call of GetTermChildren.
func (mr *MockStoreMockRecorder) GetTermChildren(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTermChildren", reflect.TypeOf((*MockStore)(nil).GetTermChildren), arg0, arg1)
}

// GetTermParents mocks base method.
func (m *MockStore) GetTermParents(arg0 context.Context, arg1 int64) ([]db.TaxonomyTerm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTermParents", arg0, arg1)
	ret0, _ := ret[0].([]db.TaxonomyTerm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTermParents indicates an expected call of GetTermParents.
func (mr *MockStoreMockRecorder) GetTermParents(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTermParents", reflect.TypeOf((*MockStore)(nil).GetTermParents), arg0, arg1)
}

// GetUser mocks base method.
func (m *MockStore) GetUser(arg0 context.Context, arg1 int64) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockStoreMockRecorder) GetUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockStore)(nil).GetUser), arg0, arg1)
}

// GetUserByEmail mocks base method.
func (m *MockStore) GetUserByEmail(arg0 context.Context, arg1 string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockStoreMockRecorder) GetUserByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockStore)(nil).GetUserByEmail), arg0, arg1)
}

// GetUserByUsername mocks base method.
func (m *MockStore) GetUserByUsername(arg0 context.Context, arg1 string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockStoreMockRecorder) GetUserByUsername(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockStore)(nil).GetUserByUsername), arg0, arg1)
}

// GetUserMediaCount mocks base method.
func (m *MockStore) GetUserMediaCount(arg0 context.Context, arg1 int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserMediaCount", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserMediaCount indicates an expected call of GetUserMediaCount.
func (mr *MockStoreMockRecorder) GetUserMediaCount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserMediaCount", reflect.TypeOf((*MockStore)(nil).GetUserMediaCount), arg0, arg1)
}

// ListMedia mocks base method.
func (m *MockStore) ListMedia(arg0 context.Context, arg1 db.ListMediaParams) ([]db.ListMediaRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMedia", arg0, arg1)
	ret0, _ := ret[0].([]db.ListMediaRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMedia indicates an expected call of ListMedia.
func (mr *MockStoreMockRecorder) ListMedia(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMedia", reflect.TypeOf((*MockStore)(nil).ListMedia), arg0, arg1)
}

// ListPostTypes mocks base method.
func (m *MockStore) ListPostTypes(arg0 context.Context) ([]db.PostType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPostTypes", arg0)
	ret0, _ := ret[0].([]db.PostType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPostTypes indicates an expected call of ListPostTypes.
func (mr *MockStoreMockRecorder) ListPostTypes(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPostTypes", reflect.TypeOf((*MockStore)(nil).ListPostTypes), arg0)
}

// ListPosts mocks base method.
func (m *MockStore) ListPosts(arg0 context.Context, arg1 db.ListPostsParams) ([]db.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPosts", arg0, arg1)
	ret0, _ := ret[0].([]db.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPosts indicates an expected call of ListPosts.
func (mr *MockStoreMockRecorder) ListPosts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPosts", reflect.TypeOf((*MockStore)(nil).ListPosts), arg0, arg1)
}

// ListPostsByType mocks base method.
func (m *MockStore) ListPostsByType(arg0 context.Context, arg1 db.ListPostsByTypeParams) ([]db.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPostsByType", arg0, arg1)
	ret0, _ := ret[0].([]db.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPostsByType indicates an expected call of ListPostsByType.
func (mr *MockStoreMockRecorder) ListPostsByType(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPostsByType", reflect.TypeOf((*MockStore)(nil).ListPostsByType), arg0, arg1)
}

// ListPostsByTypeWithAllMeta mocks base method.
func (m *MockStore) ListPostsByTypeWithAllMeta(arg0 context.Context, arg1 db.ListPostsByTypeWithAllMetaParams) ([]db.ListPostsByTypeWithAllMetaRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPostsByTypeWithAllMeta", arg0, arg1)
	ret0, _ := ret[0].([]db.ListPostsByTypeWithAllMetaRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPostsByTypeWithAllMeta indicates an expected call of ListPostsByTypeWithAllMeta.
func (mr *MockStoreMockRecorder) ListPostsByTypeWithAllMeta(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPostsByTypeWithAllMeta", reflect.TypeOf((*MockStore)(nil).ListPostsByTypeWithAllMeta), arg0, arg1)
}

// ListPostsByTypeWithMeta mocks base method.
func (m *MockStore) ListPostsByTypeWithMeta(arg0 context.Context, arg1 db.ListPostsByTypeWithMetaParams) ([]db.ListPostsByTypeWithMetaRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPostsByTypeWithMeta", arg0, arg1)
	ret0, _ := ret[0].([]db.ListPostsByTypeWithMetaRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPostsByTypeWithMeta indicates an expected call of ListPostsByTypeWithMeta.
func (mr *MockStoreMockRecorder) ListPostsByTypeWithMeta(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPostsByTypeWithMeta", reflect.TypeOf((*MockStore)(nil).ListPostsByTypeWithMeta), arg0, arg1)
}

// ListPostsWithAllMeta mocks base method.
func (m *MockStore) ListPostsWithAllMeta(arg0 context.Context, arg1 db.ListPostsWithAllMetaParams) ([]db.ListPostsWithAllMetaRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPostsWithAllMeta", arg0, arg1)
	ret0, _ := ret[0].([]db.ListPostsWithAllMetaRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPostsWithAllMeta indicates an expected call of ListPostsWithAllMeta.
func (mr *MockStoreMockRecorder) ListPostsWithAllMeta(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPostsWithAllMeta", reflect.TypeOf((*MockStore)(nil).ListPostsWithAllMeta), arg0, arg1)
}

// ListPostsWithMedia mocks base method.
func (m *MockStore) ListPostsWithMedia(arg0 context.Context, arg1 db.ListPostsWithMediaParams) ([]db.ListPostsWithMediaRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPostsWithMedia", arg0, arg1)
	ret0, _ := ret[0].([]db.ListPostsWithMediaRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPostsWithMedia indicates an expected call of ListPostsWithMedia.
func (mr *MockStoreMockRecorder) ListPostsWithMedia(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPostsWithMedia", reflect.TypeOf((*MockStore)(nil).ListPostsWithMedia), arg0, arg1)
}

// ListPostsWithMeta mocks base method.
func (m *MockStore) ListPostsWithMeta(arg0 context.Context, arg1 db.ListPostsWithMetaParams) ([]db.ListPostsWithMetaRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPostsWithMeta", arg0, arg1)
	ret0, _ := ret[0].([]db.ListPostsWithMetaRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPostsWithMeta indicates an expected call of ListPostsWithMeta.
func (mr *MockStoreMockRecorder) ListPostsWithMeta(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPostsWithMeta", reflect.TypeOf((*MockStore)(nil).ListPostsWithMeta), arg0, arg1)
}

// ListSessionsByUser mocks base method.
func (m *MockStore) ListSessionsByUser(arg0 context.Context, arg1 int64) ([]db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessionsByUser", arg0, arg1)
	ret0, _ := ret[0].([]db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSessionsByUser indicates an expected call of ListSessionsByUser.
func (mr *MockStoreMockRecorder) ListSessionsByUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessionsByUser", reflect.TypeOf((*MockStore)(nil).ListSessionsByUser), arg0, arg1)
}

// ListSessionsByUsername mocks base method.
func (m *MockStore) ListSessionsByUsername(arg0 context.Context, arg1 string) ([]db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessionsByUsername", arg0, arg1)
	ret0, _ := ret[0].([]db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSessionsByUsername indicates an expected call of ListSessionsByUsername.
func (mr *MockStoreMockRecorder) ListSessionsByUsername(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessionsByUsername", reflect.TypeOf((*MockStore)(nil).ListSessionsByUsername), arg0, arg1)
}

// ListTaxonomyTermsByType mocks base method.
func (m *MockStore) ListTaxonomyTermsByType(arg0 context.Context, arg1 db.ListTaxonomyTermsByTypeParams) ([]db.ListTaxonomyTermsByTypeRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTaxonomyTermsByType", arg0, arg1)
	ret0, _ := ret[0].([]db.ListTaxonomyTermsByTypeRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTaxonomyTermsByType indicates an expected call of ListTaxonomyTermsByType.
func (mr *MockStoreMockRecorder) ListTaxonomyTermsByType(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTaxonomyTermsByType", reflect.TypeOf((*MockStore)(nil).ListTaxonomyTermsByType), arg0, arg1)
}

// ListTaxonomyTypes mocks base method.
func (m *MockStore) ListTaxonomyTypes(arg0 context.Context) ([]db.TaxonomyType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTaxonomyTypes", arg0)
	ret0, _ := ret[0].([]db.TaxonomyType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTaxonomyTypes indicates an expected call of ListTaxonomyTypes.
func (mr *MockStoreMockRecorder) ListTaxonomyTypes(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTaxonomyTypes", reflect.TypeOf((*MockStore)(nil).ListTaxonomyTypes), arg0)
}

// ListUsers mocks base method.
func (m *MockStore) ListUsers(arg0 context.Context, arg1 db.ListUsersParams) ([]db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", arg0, arg1)
	ret0, _ := ret[0].([]db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockStoreMockRecorder) ListUsers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockStore)(nil).ListUsers), arg0, arg1)
}

// RemoveAllPostTaxonomies mocks base method.
func (m *MockStore) RemoveAllPostTaxonomies(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAllPostTaxonomies", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAllPostTaxonomies indicates an expected call of RemoveAllPostTaxonomies.
func (mr *MockStoreMockRecorder) RemoveAllPostTaxonomies(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAllPostTaxonomies", reflect.TypeOf((*MockStore)(nil).RemoveAllPostTaxonomies), arg0, arg1)
}

// RemoveAllPostTaxonomiesByTerm mocks base method.
func (m *MockStore) RemoveAllPostTaxonomiesByTerm(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAllPostTaxonomiesByTerm", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAllPostTaxonomiesByTerm indicates an expected call of RemoveAllPostTaxonomiesByTerm.
func (mr *MockStoreMockRecorder) RemoveAllPostTaxonomiesByTerm(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAllPostTaxonomiesByTerm", reflect.TypeOf((*MockStore)(nil).RemoveAllPostTaxonomiesByTerm), arg0, arg1)
}

// RemovePostFromTaxonomyTerm mocks base method.
func (m *MockStore) RemovePostFromTaxonomyTerm(arg0 context.Context, arg1 db.RemovePostFromTaxonomyTermParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePostFromTaxonomyTerm", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemovePostFromTaxonomyTerm indicates an expected call of RemovePostFromTaxonomyTerm.
func (mr *MockStoreMockRecorder) RemovePostFromTaxonomyTerm(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePostFromTaxonomyTerm", reflect.TypeOf((*MockStore)(nil).RemovePostFromTaxonomyTerm), arg0, arg1)
}

// RotateToNewSession mocks base method.
func (m *MockStore) RotateToNewSession(arg0 context.Context, arg1 db.RotateToNewSessionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateToNewSession", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RotateToNewSession indicates an expected call of RotateToNewSession.
func (mr *MockStoreMockRecorder) RotateToNewSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateToNewSession", reflect.TypeOf((*MockStore)(nil).RotateToNewSession), arg0, arg1)
}

// SearchMediaByName mocks base method.
func (m *MockStore) SearchMediaByName(arg0 context.Context, arg1 db.SearchMediaByNameParams) ([]db.SearchMediaByNameRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchMediaByName", arg0, arg1)
	ret0, _ := ret[0].([]db.SearchMediaByNameRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchMediaByName indicates an expected call of SearchMediaByName.
func (mr *MockStoreMockRecorder) SearchMediaByName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchMediaByName", reflect.TypeOf((*MockStore)(nil).SearchMediaByName), arg0, arg1)
}

// SearchTaxonomyTerms mocks base method.
func (m *MockStore) SearchTaxonomyTerms(arg0 context.Context, arg1 db.SearchTaxonomyTermsParams) ([]db.SearchTaxonomyTermsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchTaxonomyTerms", arg0, arg1)
	ret0, _ := ret[0].([]db.SearchTaxonomyTermsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchTaxonomyTerms indicates an expected call of SearchTaxonomyTerms.
func (mr *MockStoreMockRecorder) SearchTaxonomyTerms(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchTaxonomyTerms", reflect.TypeOf((*MockStore)(nil).SearchTaxonomyTerms), arg0, arg1)
}

// TransferMediaToUser mocks base method.
func (m *MockStore) TransferMediaToUser(arg0 context.Context, arg1 db.TransferMediaToUserParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferMediaToUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// TransferMediaToUser indicates an expected call of TransferMediaToUser.
func (mr *MockStoreMockRecorder) TransferMediaToUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferMediaToUser", reflect.TypeOf((*MockStore)(nil).TransferMediaToUser), arg0, arg1)
}

// TransferPostsToAdmin mocks base method.
func (m *MockStore) TransferPostsToAdmin(arg0 context.Context, arg1 db.TransferPostsToAdminParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferPostsToAdmin", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// TransferPostsToAdmin indicates an expected call of TransferPostsToAdmin.
func (mr *MockStoreMockRecorder) TransferPostsToAdmin(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferPostsToAdmin", reflect.TypeOf((*MockStore)(nil).TransferPostsToAdmin), arg0, arg1)
}

// UpdateMedia mocks base method.
func (m *MockStore) UpdateMedia(arg0 context.Context, arg1 db.UpdateMediaParams) (db.Medium, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMedia", arg0, arg1)
	ret0, _ := ret[0].(db.Medium)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMedia indicates an expected call of UpdateMedia.
func (mr *MockStoreMockRecorder) UpdateMedia(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMedia", reflect.TypeOf((*MockStore)(nil).UpdateMedia), arg0, arg1)
}

// UpdatePost mocks base method.
func (m *MockStore) UpdatePost(arg0 context.Context, arg1 db.UpdatePostParams) (db.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePost", arg0, arg1)
	ret0, _ := ret[0].(db.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePost indicates an expected call of UpdatePost.
func (mr *MockStoreMockRecorder) UpdatePost(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePost", reflect.TypeOf((*MockStore)(nil).UpdatePost), arg0, arg1)
}

// UpdatePostMediaTx mocks base method.
func (m *MockStore) UpdatePostMediaTx(arg0 context.Context, arg1 db.UpdatePostMediaTxParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePostMediaTx", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePostMediaTx indicates an expected call of UpdatePostMediaTx.
func (mr *MockStoreMockRecorder) UpdatePostMediaTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePostMediaTx", reflect.TypeOf((*MockStore)(nil).UpdatePostMediaTx), arg0, arg1)
}

// UpdatePostMeta mocks base method.
func (m *MockStore) UpdatePostMeta(arg0 context.Context, arg1 db.UpdatePostMetaParams) (db.PostMetum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePostMeta", arg0, arg1)
	ret0, _ := ret[0].(db.PostMetum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePostMeta indicates an expected call of UpdatePostMeta.
func (mr *MockStoreMockRecorder) UpdatePostMeta(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePostMeta", reflect.TypeOf((*MockStore)(nil).UpdatePostMeta), arg0, arg1)
}

// UpdatePostTaxonomyTermsTx mocks base method.
func (m *MockStore) UpdatePostTaxonomyTermsTx(arg0 context.Context, arg1 db.UpdatePostTaxonomyTermsTxParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePostTaxonomyTermsTx", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePostTaxonomyTermsTx indicates an expected call of UpdatePostTaxonomyTermsTx.
func (mr *MockStoreMockRecorder) UpdatePostTaxonomyTermsTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePostTaxonomyTermsTx", reflect.TypeOf((*MockStore)(nil).UpdatePostTaxonomyTermsTx), arg0, arg1)
}

// UpdatePostType mocks base method.
func (m *MockStore) UpdatePostType(arg0 context.Context, arg1 db.UpdatePostTypeParams) (db.PostType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePostType", arg0, arg1)
	ret0, _ := ret[0].(db.PostType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePostType indicates an expected call of UpdatePostType.
func (mr *MockStoreMockRecorder) UpdatePostType(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePostType", reflect.TypeOf((*MockStore)(nil).UpdatePostType), arg0, arg1)
}

// UpdatePostsUsername mocks base method.
func (m *MockStore) UpdatePostsUsername(arg0 context.Context, arg1 db.UpdatePostsUsernameParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePostsUsername", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePostsUsername indicates an expected call of UpdatePostsUsername.
func (mr *MockStoreMockRecorder) UpdatePostsUsername(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePostsUsername", reflect.TypeOf((*MockStore)(nil).UpdatePostsUsername), arg0, arg1)
}

// UpdateSession mocks base method.
func (m *MockStore) UpdateSession(arg0 context.Context, arg1 db.UpdateSessionParams) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSession", arg0, arg1)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSession indicates an expected call of UpdateSession.
func (mr *MockStoreMockRecorder) UpdateSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSession", reflect.TypeOf((*MockStore)(nil).UpdateSession), arg0, arg1)
}

// UpdateSessionsUsername mocks base method.
func (m *MockStore) UpdateSessionsUsername(arg0 context.Context, arg1 db.UpdateSessionsUsernameParams) ([]db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSessionsUsername", arg0, arg1)
	ret0, _ := ret[0].([]db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSessionsUsername indicates an expected call of UpdateSessionsUsername.
func (mr *MockStoreMockRecorder) UpdateSessionsUsername(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSessionsUsername", reflect.TypeOf((*MockStore)(nil).UpdateSessionsUsername), arg0, arg1)
}

// UpdateTaxonomyTerm mocks base method.
func (m *MockStore) UpdateTaxonomyTerm(arg0 context.Context, arg1 db.UpdateTaxonomyTermParams) (db.TaxonomyTerm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaxonomyTerm", arg0, arg1)
	ret0, _ := ret[0].(db.TaxonomyTerm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTaxonomyTerm indicates an expected call of UpdateTaxonomyTerm.
func (mr *MockStoreMockRecorder) UpdateTaxonomyTerm(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaxonomyTerm", reflect.TypeOf((*MockStore)(nil).UpdateTaxonomyTerm), arg0, arg1)
}

// UpdateTaxonomyType mocks base method.
func (m *MockStore) UpdateTaxonomyType(arg0 context.Context, arg1 db.UpdateTaxonomyTypeParams) (db.TaxonomyType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaxonomyType", arg0, arg1)
	ret0, _ := ret[0].(db.TaxonomyType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTaxonomyType indicates an expected call of UpdateTaxonomyType.
func (mr *MockStoreMockRecorder) UpdateTaxonomyType(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaxonomyType", reflect.TypeOf((*MockStore)(nil).UpdateTaxonomyType), arg0, arg1)
}

// UpdateUser mocks base method.
func (m *MockStore) UpdateUser(arg0 context.Context, arg1 db.UpdateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockStoreMockRecorder) UpdateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockStore)(nil).UpdateUser), arg0, arg1)
}

// UpdateUserPostsOwnership mocks base method.
func (m *MockStore) UpdateUserPostsOwnership(arg0 context.Context, arg1 db.UpdateUserPostsOwnershipParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPostsOwnership", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserPostsOwnership indicates an expected call of UpdateUserPostsOwnership.
func (mr *MockStoreMockRecorder) UpdateUserPostsOwnership(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPostsOwnership", reflect.TypeOf((*MockStore)(nil).UpdateUserPostsOwnership), arg0, arg1)
}

// UpdateUserTx mocks base method.
func (m *MockStore) UpdateUserTx(arg0 context.Context, arg1 db.UpdateUserTxParams) (db.UpdateUserTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserTx", arg0, arg1)
	ret0, _ := ret[0].(db.UpdateUserTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserTx indicates an expected call of UpdateUserTx.
func (mr *MockStoreMockRecorder) UpdateUserTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserTx", reflect.TypeOf((*MockStore)(nil).UpdateUserTx), arg0, arg1)
}

// UpsertPostMeta mocks base method.
func (m *MockStore) UpsertPostMeta(arg0 context.Context, arg1 db.UpsertPostMetaParams) (db.PostMetum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertPostMeta", arg0, arg1)
	ret0, _ := ret[0].(db.PostMetum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertPostMeta indicates an expected call of UpsertPostMeta.
func (mr *MockStoreMockRecorder) UpsertPostMeta(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertPostMeta", reflect.TypeOf((*MockStore)(nil).UpsertPostMeta), arg0, arg1)
}
